#!/usr/bin/env python3
"""Assemble R176_Assembled.lean = Site_176.lean + the appendices of R176_HSUCC / R176_SMOOTH / R176_LEDGER
+ the assembler's composition section (generated by gen_R176_compose.py).
Checks: (1) the first 4143 lines of every unit file are byte-identical to Site_176.lean; (2) every declaration
of an appendix carries the unit prefix (r176h_ / r176s_ / r176l_) and no structural line (import, set_option,
global attribute) is added; (3) no duplicate fully-qualified declaration name; (4) statement-identical pairs
across units are reported.  Usage: python3 assemble_R176.py [dir]  (default: the script's directory)."""
import os, re, sys, subprocess, difflib
D = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
NSITE = 4143
site = open(os.path.join(D, 'Site_176.lean'), encoding='utf-8').read().split('\n')
assert len(site) == NSITE + 1 and site[-1] == '', len(site)   # file ends with a newline
units = [('R176_HSUCC.lean', 'r176h_'), ('R176_SMOOTH.lean', 'r176s_'), ('R176_LEDGER.lean', 'r176l_')]
decl_re = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:open\s+[^\n]*?\bin\s+)?(?:private\s+|protected\s+|noncomputable\s+|nonrec\s+|partial\s+)*(theorem|lemma|def|abbrev|instance|structure|inductive|class|opaque|axiom)\s+([^\s(:{\[]+)')
bad_struct = re.compile(r'^\s*(import|set_option|universe|macro|syntax|notation|elab)\b')
attr_re = re.compile(r'^\s*attribute\s*\[')
out = list(site[:-1])
violations = []
appendix_decls = {}
for fn, prefix in units:
    lines = open(os.path.join(D, fn), encoding='utf-8').read().split('\n')
    if lines[:NSITE] != site[:NSITE]:
        violations.append((fn, 'prefix (lines 1-%d) differs from Site_176.lean' % NSITE))
        for l in difflib.unified_diff(site[:NSITE], lines[:NSITE], lineterm='', n=0):
            print('   ', l)
    app = lines[NSITE:]
    if app and app[-1] == '': app = app[:-1]
    names = []
    for k, l in enumerate(app, NSITE + 1):
        m = decl_re.match(l)
        if m:
            name = m.group(2)
            names.append((name, k))
            if not name.startswith(prefix) and not name.startswith('_root_.' + prefix):
                violations.append((fn, 'unprefixed declaration %r at line %d' % (name, k)))
        if bad_struct.match(l):
            violations.append((fn, 'structural line at %d: %r' % (k, l)))
        if attr_re.match(l) and 'local instance' not in l:
            violations.append((fn, 'non-local attribute at %d: %r' % (k, l)))
    appendix_decls[fn] = names
    out.extend(app)
    print('%s: appendix %d lines, %d declarations, all prefixed %s' % (fn, len(app), len(names),
          all(n.startswith(prefix) for n, _ in names)))
# composition section
comp_path = os.path.join(D, 'R176_compose_part.lean')
subprocess.run([sys.executable, os.path.join(D, 'gen_R176_compose.py'), os.path.join(D, 'R176_LEDGER.lean'), comp_path], check=True)
comp = open(comp_path, encoding='utf-8').read().split('\n')
if comp and comp[-1] == '': comp = comp[:-1]
cnames = [(decl_re.match(l).group(2), k) for k, l in enumerate(comp, 1) if decl_re.match(l)]
for n_, k in cnames:
    if not n_.startswith('r176_'):
        violations.append(('compose', 'unprefixed %r at %d' % (n_, k)))
print('composition section: %d lines, %d declarations (r176_)' % (len(comp), len(cnames)))
out.extend(comp)
# duplicates (all in namespace RProof)
allnames = {}
for fn, names in appendix_decls.items():
    for n_, k in names: allnames.setdefault(n_, []).append((fn, k))
for n_, k in cnames: allnames.setdefault(n_, []).append(('compose', k))
sitenames = [decl_re.match(l).group(2) for l in site if decl_re.match(l)]
for n_ in sitenames: allnames.setdefault(n_, []).append(('Site_176', 0))
# the frozen skeleton has same-short-name declarations in different namespaces (BigonData.eIn / Cut.eIn ...);
# only duplicates involving an appendix or the composition section are violations
dups = {k: v for k, v in allnames.items() if len(v) > 1 and any(f != 'Site_176' for f, _ in v)}
if dups:
    violations.append(('ALL', 'duplicate declaration names: %r' % dups))
if violations:
    print('VIOLATIONS:')
    for v in violations: print('  ', v)
    sys.exit(2)
open(os.path.join(D, 'R176_Assembled.lean'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('assembled %d lines -> R176_Assembled.lean' % len(out))
# statement-identical pairs across units (informational)
def stmt(lines, i):
    s = []
    for l in lines[i:]:
        s.append(l)
        if ':=' in l: break
    t = ' '.join(s)
    return re.sub(r'\s+', ' ', t.split(':=')[0])
stmts = {}
for fn, prefix in units:
    lines = open(os.path.join(D, fn), encoding='utf-8').read().split('\n')
    for k in range(NSITE, len(lines)):
        m = decl_re.match(lines[k])
        if m:
            body = stmt(lines, k)
            key = re.sub(re.escape(m.group(2)), 'NAME', body, count=1)
            stmts.setdefault(key, []).append((fn, m.group(2)))
pairs = [v for k, v in stmts.items() if len({f for f, _ in v}) > 1 and k.strip() not in ('def NAME : Prop', 'theorem NAME : Prop')]
print('statement-identical declarations across units (modulo the name): %d' % len(pairs))
for p in pairs: print('   ', p)
