#!/usr/bin/env python3
"""Assemble R176W2_Assembled.lean = R176_Port_draft.lean + the wave-2 unit appendices (CURL r176c_, OUTER r176o_,
MIXED r176m_) + the assembler's section (R176W2_compose_part.lean: the mirrored bridge `r176a_mixed_bridge'_proof`,
generated from the MIXED proof) + the row block (R176W2_row_part.lean: `RProof.extreme_transport`).
Checks: (1) CURL/OUTER = draft lines 1-6336 + appendix + draft lines 6337-6339 (`end`/``/`end RProof`), byte-identical;
MIXED = draft lines 1-6339 + appendix; (2) every appended declaration carries its unit prefix; no import/set_option/
global attribute added; (3) no duplicate fully-qualified name.  Also emits port/R176/RProof/ExtremeTransportUnits.lean
(assembled minus the row block, new header) and port/R176/RProof/ExtremeTransport.lean (import + row block).
Usage: python3 assemble_R176W2.py [--no-port]"""
import os, re, sys
D = os.path.dirname(os.path.abspath(__file__))
def rd(fn): return open(os.path.join(D, fn), encoding='utf-8').read().split('\n')
draft = rd('R176_Port_draft.lean'); assert len(draft) == 6340 and draft[-1] == ''
draft = draft[:-1]                       # 6339 lines
assert draft[6336:6339] == ['end', '', 'end RProof'], draft[6336:6339]
decl_re = re.compile(r'^\s*(?:@\[[^\]]*\]\s*)?(?:open\s+[^\n]*?\bin\s+)?(?:private\s+|protected\s+|noncomputable\s+|nonrec\s+|partial\s+)*(theorem|lemma|def|abbrev|instance|structure|inductive|class|opaque|axiom)\s+([^\s(:{\[]+)')
bad_struct = re.compile(r'^\s*(import|set_option|universe|macro|syntax|notation|elab)\b')
attr_re = re.compile(r'^\s*attribute\s*\[')
viol = []; names = {}
def check(app, fn, prefix, base):
    got = []
    for k, l in enumerate(app, base + 1):
        m = decl_re.match(l)
        if m:
            nm = m.group(2); got.append((nm, k))
            if not (nm.startswith(prefix) or nm.startswith('_root_.' + prefix)):
                viol.append((fn, 'unprefixed %r at %d' % (nm, k)))
            names.setdefault(nm, []).append((fn, k))
        if bad_struct.match(l): viol.append((fn, 'structural line %d: %r' % (k, l)))
        if attr_re.match(l) and 'local instance' not in l: viol.append((fn, 'non-local attribute %d: %r' % (k, l)))
        if re.search(r'\bsorry\b|#print|#eval|#check', l): viol.append((fn, 'forbidden string at %d: %r' % (k, l[:80])))
    print('%s: appendix %d lines, %d declarations (%s)' % (fn, len(app), len(got), prefix))
    return got
# CURL, OUTER: inserted before the trailing `end` / `end RProof`
apps = {}
for fn, prefix, cut in [('R176W2_CURL.lean', 'r176c_', 6336), ('R176W2_OUTER.lean', 'r176o_', 6336)]:
    u = rd(fn); assert u[-1] == ''; u = u[:-1]
    assert u[:cut] == draft[:cut], fn + ': prefix differs'
    assert u[-3:] == draft[6336:6339], fn + ': tail differs'
    apps[fn] = u[cut:-3]; check(apps[fn], fn, prefix, cut)
u = rd('R176W2_MIXED.lean'); assert u[-1] == ''; u = u[:-1]
assert u[:6339] == draft, 'MIXED: prefix differs'
apps['R176W2_MIXED.lean'] = u[6339:]; check(apps['R176W2_MIXED.lean'], 'R176W2_MIXED.lean', 'r176m_', 6339)
comp = rd('R176W2_compose_part.lean');  comp = comp[:-1] if comp[-1] == '' else comp
row = rd('R176W2_row_part.lean');       row = row[:-1] if row[-1] == '' else row
check(comp, 'R176W2_compose_part.lean', 'r176a_', 0)
rown = [(decl_re.match(l).group(2), k) for k, l in enumerate(row, 1) if decl_re.match(l)]
print('row block: %d lines, declarations %s' % (len(row), rown))
for nm, _ in rown: names.setdefault(nm, []).append(('row', 0))
for l in draft:
    m = decl_re.match(l)
    if m: names.setdefault(m.group(2), []).append(('draft', 0))
dups = {k: v for k, v in names.items() if len(v) > 1 and any(f != 'draft' for f, _ in v)}
if dups: viol.append(('ALL', 'duplicate names: %r' % dups))
if viol:
    print('VIOLATIONS:'); [print('  ', v) for v in viol]; sys.exit(2)
HDR = ('-- R176W2_Assembled.lean — row-176 wave-2 assembler, 2026-09-15: R176_Port_draft.lean (lines 1-6336 and 6337-6339 verbatim) '
       'with the wave-2 unit appendices spliced in — CURL (r176c_, R176W2_CURL.lean 6337-6706) and OUTER (r176o_, R176W2_OUTER.lean '
       '6337-7981) inside the draft\'s final `namespace RProof`/`noncomputable section`, MIXED (r176m_, R176W2_MIXED.lean 6340-6835) '
       'after `end RProof` — then the assembler\'s section (r176a_: the mirrored (14)-bridge, from the MIXED proof) and the row block '
       '(RProof.extreme_transport).  Generated by assemble_R176W2.py; see R176W2_ASSEMBLY_REPORT.md.')
out = [HDR] + draft[1:6336] + apps['R176W2_CURL.lean'] + apps['R176W2_OUTER.lean'] + draft[6336:6339] + apps['R176W2_MIXED.lean'] + comp + row
open(os.path.join(D, 'R176W2_Assembled.lean'), 'w', encoding='utf-8').write('\n'.join(out) + '\n')
print('assembled %d lines -> R176W2_Assembled.lean (row block at lines %d-%d)' % (len(out), len(out) - len(row) + 1, len(out)))
if '--no-port' in sys.argv: sys.exit(0)
# ---- port files ----
P = os.path.join(D, 'port', 'R176', 'RProof'); os.makedirs(P, exist_ok=True)
UH = open(os.path.join(D, 'R176W2_units_header.txt'), encoding='utf-8').read().rstrip('\n').split('\n')
units = UH + draft[1:6336] + apps['R176W2_CURL.lean'] + apps['R176W2_OUTER.lean'] + draft[6336:6339] + apps['R176W2_MIXED.lean'] + comp
open(os.path.join(P, 'ExtremeTransportUnits.lean'), 'w', encoding='utf-8').write('\n'.join(units) + '\n')
RH = open(os.path.join(D, 'R176W2_row_header.txt'), encoding='utf-8').read().rstrip('\n').split('\n')
open(os.path.join(P, 'ExtremeTransport.lean'), 'w', encoding='utf-8').write('\n'.join(RH + row) + '\n')
for f in ('ExtremeTransportUnits.lean', 'ExtremeTransport.lean'):
    t = open(os.path.join(P, f), encoding='utf-8').read()
    bad = [w for w in ('sorry', '#print', '#eval') if w in t]
    print('port/R176/RProof/%s: %d lines, forbidden strings: %s' % (f, t.count('\n'), bad or 'none'))
    if bad: sys.exit(3)
