from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/farout-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256']
for key in ['root_receipts_sha256','root_files_sha256','SM_closure_files_sha256','inherited_review_binding','example_files_sha256']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
assert sha(p['trace'])==p['trace_sha256']
priorfile='work/reviews/nearfar-factorization-far-only-prototype.json';prior=load(priorfile)
assert sha(priorfile)=='6a680e4851f116f42e77593f75ce1fbbe9683f5ec8b519cdcc3cef11dd6fe881'
fragmentfile='work/reviews/marked-transport-independent.json';fragment=load(fragmentfile)
assert sha(fragmentfile)=='660b35e9ce99e04fce1ad1a722652b388806cdf0df55574b09804a66a9f71174'
for f,h in fragment['files_sha256'].items():assert sha(f)==h
for d in fragment['reviewed_declarations']:
 s=''.join((base/d['path']).read_text().splitlines(keepends=True)[d['first_line']-1:d['last_line']])
 assert s==d['text'] and sha256(s.encode()).hexdigest()==d['sha256']
logfile='work/checks/farout-review-types.log';s=(base/logfile).read_text()
assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==127 and len(examples)==48
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 i=m.start();j=s.index("'"+n+"'",i);types[n]=s[i:j].strip()
oldtypes=load('work/checks/refined-weights-reviewed-types.json')['types'];assert len(oldtypes)==93
assert all(types[n]==t for n,t in oldtypes.items())
typefile='work/checks/farout-reviewed-types.json'
typehashes={n:sha256(t.encode()).hexdigest() for n,t in types.items()}
write(typefile,{'types':types,'type_sha256':typehashes,'axioms':axioms,'checked_declarations':names,'new_checked_declarations':p['new_checked_declarations'],'all_93_predecessor_types_unchanged':True,'consumer_count':48,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/farout-review-closure.json'
write(closurefile,{'status':'independent first kernel passed; full source lemma reviewed externally','source':p['source'],'source_sha256':p['source_sha256'],
 'SM_import_roots':p['SM_import_roots'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':20,'reviewed_files_sha256':reviewed,
 'embedded_frozen_bodies':{n:sha('work/checks/'+n+'.body.lean') for n in p['body_order']},'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],
 'fresh_fragment_review':fragmentfile,'fresh_fragment_review_sha256':sha(fragmentfile),'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),
 'scope':'All lem:farout clauses, including actual contiguous-word restriction, all raw compositions, triangular inverse restriction and the local-G1 tree coefficient at the physical last-to-first closing edge. Canonical port and canonical semantic review remain pending.'})
roots={}
for n in p['body_order']:
 f='work/checks/'+n+'-prototype-result.json';roots[n]=dict(load(f),receipt=f,receipt_sha256=sha(f))
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),
 'independent_kernel_command':'lake env lean ../checks/farout-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':True,
 'checked_declarations':names,'declaration_count':127,'new_declaration_count':34,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':48,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},
 'all_93_predecessor_types_unchanged':True,'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),
 'root_successful_results':roots,'fresh_fragment_statement_review':fragmentfile,'fresh_fragment_statement_review_sha256':sha(fragmentfile),
 'scope_note':'Exact twelve frozen implementation bodies are compiled over their actual twenty-module canonical dependency closure. The full original aggregate and 126 other declarations receive printed types and axiom traces. All 48 consumers pass, including 18 new physical-domain, local-root and complete-aggregate checks. Prior root proof-elaboration failures remain disclosed in bound receipts; this independent full-source check passed first.'}
justifications=[x for x in prior['mathematical_justification'] if x['clause']!='Remaining original source clause']
justifications += [
 {'clause':'Complete interval and composition domains remain unchanged','assessment':'BoundaryInterval is every pair of Fin n positions with left<right; leaves is right-left. IntervalComposition has arbitrary positive natural part count, a strictly increasing Fin(parts+1) cut map, and exact first/last endpoints. Finiteness and the parts<n bound are derived, not assumptions narrowing this raw domain. TripleArray and IntervalArray are unrestricted functions on their actual finite source domains. The current trace rechecks the previously reviewed full factorization on these same definitions, and all 93 predecessor printed types are byte-for-byte unchanged.'},
 {'clause':'All local positions and all physical subintervals','assessment':'globalPosition sends a local position k to J.left+k. Its bound uses k<=J.leaves=J.right-J.left, so every output lies between J.left and J.right. localPosition subtracts J.left from any physical position within those bounds. The two proved inverse equations and strict monotonicity establish exact ordered coverage. The independent existence-and-uniqueness consumer verifies every physical position occurs once. A second consumer constructs a local interval from any original interval contained in J, proves its endpoints remain strictly ordered after subtraction, and recovers the entire original interval. Thus the restriction is not limited to a selected or assumed collection of subintervals. Another consumer verifies that translation preserves the actual leaf count.'},
 {'clause':'Every raw composition and every translated sample','assessment':'liftComposition keeps the original natural part count and cut-index type and translates each actual cut by J.left. lowerComposition keeps the same part count and subtracts J.left from every cut; all cuts are in J because first/last and strict monotonicity bound them inside the translated local interval. The first/last equations and strict ordering are proved. Raw composition extensionality then yields both inverse laws, including dependent cut maps, and restrictionEquiv covers every composition in both directions. Independent consumers verify all part counts and cut values, exact unary preservation and full finite cardinality. The part, nearTriple and farTriple equations are equalities of the actual intervals/triples. Independent sample and product consumers check arbitrary arrays at the true neighboring positions, global endpoints of the current subinterval, and every actual child interval. No coefficient or summand is discarded.'},
 {'clause':'All coordinate equations and their unique inverses commute with restriction','assessment':'restrictTripleArray and restrictIntervalArray are plain composition with the actual translation maps. nearFarTransform_restrict reindexes the full local composition sum through restrictionEquiv. Corresponding summands are definitionally identical because counts, all near/far samples and every child interval are preserved. Hence this holds for arbitrary D,H,X over every CommRing with invertible two. Applying it to the proved global inverse solution and using triangular uniqueness identifies the restriction of the actual inverse with the independently constructed local inverse, for every target Y. Adjacency is invariant under adding J.left, so the E array also restricts exactly. These results give exact restriction of both c=F_H inverse(E) and B=F_(-H)(c); no geometric or G1 assumption enters this algebraic restriction proof. The independent local-inverse consumer verifies the equation directly.'},
 {'clause':'Actual restricted word and directed physical root','assessment':'restrictedWordTuple labels the local polygon by Q(j)=a_(J.left+(j-1 mod m)), with m=J.leaves+1. The cyclic subtraction makes Q(0)=a_j and Q(1)=a_i. The complete boundary word at local root zero is proved to be a_i,...,a_j, position by position, rather than merely sign-equivalent to it. Consequently edge Q 0=Q(1)-Q(0)=a_i-a_j is precisely the directed closing edge from a_j to a_i. The independent combined consumer extracts all positions, both endpoint labels and the actual displacement together. This is an allowed labelled representative of the source endpoint polygon, consistent with the explicit formalization permission in sm-1-polygons lines55-60 and the source boundary/root convention.'},
 {'clause':'Exact geometric restriction without an assumed sign agreement','assessment':'geometricBoundaryArray_restrictedWord unfolds the actual reversed chirotope sample and replaces each of its three local boundary vertices using the full boundary-word equality. Thus its determinant, sign, integer cast and scalar embedding are literally the restriction of the same physical global geometry. The equality requires no genericity assumption. The independent local-c consumer combines it with algebraic restriction and identifies the restriction of the original far-only coordinate array with nearFarInverse(0,H_local)(E_local). No new geometric array, unproved compatibility premise or global G1 requirement is substituted.'},
 {'clause':'Local G1 is exactly sufficient for the nonleaf tree coefficient','assessment':'For J.leaves>=2 the restricted word has m=J.leaves+1>=3; this bound is proved, and the local NeZero instance is available because m is a successor. Translating its full interval yields J itself. The actual farOnlyOutput restriction equation at that local full interval, exact geometric-array restriction, and the already proved geometric full-root theorem on Q give B_J equal to the cast treeCoefficient Q hlocal 0. The only geometric premise in this theorem is G1(Q), precisely the source condition on the closed endpoint word. The global tuple P need not satisfy G1. An independent consumer extracts this conclusion directly from SM.farout with no G1(P) parameter, while another verifies the local vertex-count bound. Together with the physical directed-root identity this proves source lines163-165 and its proof213-226.'},
 {'clause':'Full original aggregate includes each printed clause','assessment':'SM.farout first quantifies over every arbitrary D,H and supplies actual MvPolynomial inverse coordinates with both evaluation identities, plus Phi=F_H composed with G_D as maps. It then states actual geometric Phi(b)=E, A=Phi(D,-H)(b) at the full source interval, and A=F_(-H)(c) there. The next conjunct compares complete reversed-far output arrays for any two near arrays and corresponding solutions with the same H and E. Actual inverse solutions exist by the first conjunct; an independent consumer instantiates them, excluding vacuous conditional independence. The fourth conjunct gives E_J=0 on every nonleaf and E_J=B_J=1 on every leaf. The last gives the exact directed closing edge and local-G1 coefficient. Separate independent consumers extract the inverse polynomial identities, map order, geometry, complete near freedom, open leaf/nonleaf values and local root from the aggregate itself. None of these conclusions is an input premise.'},
 {'clause':'Source scope, ordinary leaf convention and absence of strengthened assumptions','assessment':'The geometric section assumes G1 and does not use G2. The implementation requires G1 only where actual geometric tree sums need it, while ring factorization and inverse results remain unrestricted. The ambient hn:3<=n is the source polygon-size assumption; NeZero n follows from it by elementary arithmetic and introduces no additional mathematical restriction. The local restricted coefficient uses only its own G1 and derived size>=3. Leaf values are open-word conventions and never invoke a two-vertex polygon tree coefficient. The arbitrary ring may have zero divisors or be trivial; no field, order or nontriviality premise is present. The scalar image of the integral source tree coefficient is evaluated in any allowed ring, as required by the half-factor formulation.'},
 {'clause':'Original source result is complete externally, not yet accepted canonically','assessment':'Unlike the earlier frozen five-body report, this exact reviewed batch includes the independently indexed restricted word, all restriction equivalences, the actual inverse-coordinate identification and the physical closing-root tree coefficient. No clause of lem:farout remains missing from these frozen external statements. However these twelve bodies are not yet installed canonical modules in this review, and no current canonical semantic hash for SM.farout is asserted. Original-source acceptance remains pending exact port, whole-project audit and independent canonical source/type verification. Earlier partial reviews remain frozen as honest evidence of their earlier scope.'}
]
d={'review_schema':'independent-full-source-prototype-review-v1','id':'farout-prototype','source_id':'lem:farout','source_line':146,
 'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':'Full lemma146-168 and proof170-227. Source section assumptions3-6; roots/compositions10-27; gates29-62; tree definition66-82; near/far definition132-144; labelled-representative permission in sm-1-polygons55-60.',
 'additional_source_sha256':prior['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910',
 'verdict':'faithful','implemented_scope_verdict':'faithful','full_source_coverage':True,'parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,
 'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declaration':'SM.farout','main_declaration_printed_type':types['SM.farout'],'main_declaration_printed_type_sha256':typehashes['SM.farout'],'main_declarations':p['new_checked_declarations'],'main_declarations_by_body':{n:p['checked_declarations_by_body'][n] for n in p['new_body_names']},
 'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},'reviewed_files_sha256':reviewed,'import_closure_roots':p['SM_import_roots'],'import_closure_file_count':20,'embedded_body_count':12,
 'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':prior['pins'],
 'reason':f'Faithful full original lem:farout external implementation. The exact polynomial inverse and full marked-refinement factorization yield whole-output near independence, actual geometric full-root output and the printed leaf/nonleaf values. Exact ordered position and raw-composition equivalences prove restriction of every coordinate equation and its inverse. The restricted tuple has precisely the original contiguous boundary word, with Q(0)=a_j and Q(1)=a_i, so its root zero is the actual directed closing edge a_j to a_i. Its nonleaf coefficient requires only local G1. Independent first kernel {session} passes 127 declarations and 48 consumers with 175 standard-or-empty axiom traces; all 93 predecessor types match. The two shared marking fragments retain explicit provenance and a fresh noncontributing reviewer report. Canonical port, audit, semantic review and original-source acceptance remain pending.',
 'mathematical_justification':justifications,
 'independence':'This reviewer independently read the complete authoritative lemma and surrounding definitions, all three new bodies and the full aggregate closure, and wrote fresh physical-domain and consumer checks. No implementation, source, declaration map, root receipt or frozen prior report was edited. The two earlier marking-transport fragments have the inherited explicit authorship limitation; their exact source/type fidelity was separately reviewed by the noncontributing /root/review_mark_transport and is bound here. This kernel supplies fresh elaborated-type and axiom evidence for those fragments as well.',
 'provenance_disclosure':prior['provenance_disclosure'],
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_and_current_semantic_audit_pending':True,'full_farout_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':[],
 'not_certified':['No canonical SM.farout semantic hash or source acceptance before exact integration, current audit and independent canonical verification.','No wall law, soft theorem, R theorem or stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/farout-prototype.json';write(out,d)
print(out,sha(out));print('PASS:127 declarations+48 consumers;175 standard-or-empty traces;93 prior types unchanged; full external source coverage; canonical acceptance pending.')
