from pathlib import Path
from hashlib import sha256
import re,json,sys,datetime
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pf='work/checks/off-leaf-contraction-review-preparation.json';p=load(pf)
for k in ['sources_sha256','SM_closure_files_sha256','all_327_canonical_SM_files_sha256','root_receipts_sha256','root_files_sha256','prior_checkpoint_bindings_sha256']:
 for f,h in p[k].items():assert sha(f)==h,(k,f)
assert sha(p['trace'])==p['trace_sha256'] and sha(p['example_file'])==p['example_file_sha256']
fresh=['work/reviews/critical-contraction-child-independent.json','work/reviews/contracted-geometric-word-independent.json',
 'work/reviews/contracted-intervals-compositions-independent.json']
assert fresh[-1] in p['prior_checkpoint_bindings_sha256']
for f in fresh:
 d=load(f)
 for x,h in d['files_sha256'].items():assert sha(x)==h,(f,x)
log='work/checks/off-leaf-contraction-review-types.log';s=(base/log).read_text()
assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==19 and len(examples)==19
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n]) <= {'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
tf='work/checks/off-leaf-contraction-reviewed-types.json'
write(tf,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,
 'checked_declarations':names,'additional_examples':examples,'trace_log':log,'trace_log_sha256':sha(log),
 'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
cf='work/checks/off-leaf-contraction-review-closure.json'
write(cf,{'source_id':p['source_id'],'sources_sha256':p['sources_sha256'],'SM_import_roots':p['SM_import_roots'],
 'SM_closure_count':p['SM_closure_count'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],
 'all_327_canonical_SM_files_sha256':p['all_327_canonical_SM_files_sha256'],'reviewed_files_sha256':reviewed,
 'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],
 'prior_checkpoint_bindings_sha256':p['prior_checkpoint_bindings_sha256'],'preparation':pf,'preparation_sha256':sha(pf),
 'trace':p['trace'],'trace_sha256':sha(p['trace']),'positions_receipt_note':p['positions_receipt_note'],'scope':p['scope']})
prior=load('work/reviews/boundary-gate-stability-prototype.json')
for f,h in prior['pins']['pin_files_sha256'].items():assert sha(f)==h
failures=p.get('prior_failed_independent_runs',[])
for f in failures:
 for k in ['source','log','examples','preparation']:f[k+'_sha256']=sha(f[k])
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),
 'independent_trace_log':log,'independent_trace_log_sha256':sha(log),
 'independent_kernel_command':'lake env lean ../checks/off-leaf-contraction-review-types.lean',
 'independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':not failures,
 'prior_failed_independent_runs':failures,'checked_declarations':names,'declaration_count':19,
 'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':19,
 'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},
 'transparent_definitions_printed':p['transparent_definitions_printed'],'supporting_types_printed':p['supporting_types_printed'],
 'reviewed_types':tf,'reviewed_types_sha256':sha(tf),'independent_closure_evidence':cf,'independent_closure_evidence_sha256':sha(cf),
 'root_successful_results':{f:load(f) for f in p['root_receipts_sha256']},'root_receipts_sha256':p['root_receipts_sha256'],
 'positions_receipt_note':p['positions_receipt_note'],'supporting_independent_reviews_sha256':{f:sha(f) for f in fresh}}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'off-leaf-contraction-prototype',
 'source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':sha(p['source']),
 'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],
 'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910',
 'verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,
 'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'main_declarations':names,'main_declarations_by_body':p['checked_declarations_by_body'],
 'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['new_body_order']},
 'reviewed_files_sha256':reviewed,'import_closure_roots':p['SM_import_roots'],'import_closure_file_count':p['SM_closure_count'],
 'embedded_body_count':10,'evidence':evidence,'pins':prior['pins'],'prior_checkpoint_bindings_sha256':p['prior_checkpoint_bindings_sha256'],
 'reason':'Faithful off-leaf inverse transport, actual contracted geometric-array identification, and explicitly conditional product-response step. Off-leaf intervals lie wholly to one side of the adjacent distinguished leaf, so expansion is a translation and every original raw composition is represented. Full equation transport and a terminating comparison of actual triangular inverse equations derive c=cQ on all such intervals. Contracted arrays omit the actual critical triple, equal the actual contracted word chirotope array at root zero, retain reversal, and yield the formal leaf value and proper rooted output. The product lemma derives its other factors from the proved inverse transport but keeps the changing-child response as an explicit induction premise. Independent19 types and19 consumers pass with standard axioms only; supporting fresh reviews are bound. No completed propagation or original theorem acceptance is asserted.',
 'mathematical_justification':[
 {'clause':'Exact distinguished leaf and side separation','assessment':'The contractedLeaf endpoints are the consecutive positions lower and lower+1. Negating containment of both endpoints in a strict interval J implies J.right<=lower or lower+1<=J.left by integer order. Thus an interval excluding the formal leaf lies entirely to one side, and touching an endpoint is allowed. The independent consumer proves the converse as well, and the two inverse consumers explicitly allow touching either endpoint. This matches the source other-child disjoint-interior condition; it does not incorrectly demand disjoint closed endpoints or assume that a general positive-length old interval can only overlap wholly.'},
 {'clause':'Exact leaf count and unit-array transport','assessment':'On the left side expandPosition is the identity on both endpoints. On the right it adds the same erasedInteriorCount to both. Subtracting those actual endpoint values preserves J.leaves exactly. The strict endpoint inequalities ensure the natural-number subtraction characterizes right=left+1 without truncation ambiguity. Therefore the source unit array, one on a single leaf and zero otherwise, is transported exactly. The independent leaf consumer checks both actual inverse values equal one when J has one leaf. No zero nonleaf right-hand side is substituted on a unary interval.'},
 {'clause':'Every original raw composition survives off the leaf','assessment':'For any raw composition of the expanded interval, every cut lies between its actual endpoints. If J is left of the distinguished leaf, all expanded cuts lie at or before the original lower endpoint; if J is right, all lie at or after the original upper endpoint. Hence all cuts satisfy SurvivingCuts automatically. offLeafCompositionEquiv consequently has the entire original raw composition type as its codomain, with no filtering subtype. Its inverse contracts the exact cut list and the independently reviewed contract/expand identities prove both round trips. The current consumer starts with an arbitrary original raw composition, not an assumed survivor, and verifies the complete round trip.'},
 {'clause':'All parts, gate samples, and zero terms are preserved','assessment':'expandComposition retains the raw part count and expands every cut. Its actual child interval, near triple, and far triple are definitionally the expanded versions of the corresponding original contracted data. contractedTripleArray is exactly precomposition by expandTriple, so the entire nearFarWeight is definitionally preserved for arbitrary independent D,H arrays. Fintype.sum_equiv then transports the full nearFarTransform, with every child factor and every raw composition including the unary one. An independent arbitrary-summand reindexing consumer permits any zero or nonzero weight, and the raw-part/child consumer verifies the exact original child count and intervals. No nonzero gate or product is canceled; the reversed-transform consumer checks the negative-H orientation too.'},
 {'clause':'Actual inverse-coordinate equality is derived, not assumed','assessment':'farOnlyCoordinates_expanded_off_leaf first transports the actual equation F_H(c(H))=E from the expanded interval, using the full transform theorem and exact unit-array transport. It compares this with the actual defining inverse equation on the contracted array. Rewriting both through the proved triangular form isolates the unary coordinate with coefficient one plus the full nonunary composition sum. For every nonunary child, the child is a subinterval of J and still excludes the distinguished leaf; recursive inverse transport applies there. The stated termination measure is J.leaves, and the kernel checks its decrease using the existing strict part_leaves_lt theorem for parts>=2. Product and sum congruence equate the two nonunary sums. Additive cancellation then gives equality of the two unary inverse coordinates. No inverse transport, propagation formula, or conditional child response is an input to this proof.'},
 {'clause':'Recursive base and every actual other-child value','assessment':'When J is one leaf, the full nonunary composition type is empty and the two triangular equations determine the unary coordinate from the same unit value. The induction never invokes a recursive call on an equal-size unary child: its recursive calls occur only in the subtype with parts>=2. The independent child consumer transports every actual child of an off-leaf interval, while separate consumers check the exact leaf base and both endpoint-touching cases. Identifying which other child excludes the distinguished leaf is supplied by the separately independently reviewed positive-interval uniqueness theorem, not by assuming the desired inverse equality.'},
 {'clause':'The contracted array omits precisely the possible critical change','assessment':'Every expanded position survives outside the deleted open critical arc. If an expanded increasing triple equaled the critical triple, its middle position would be the deleted critical middle, contradicting the surviving-position bounds and lower<middle<upper. Therefore H1 and H2 agreeing off the critical triple have identical complete contracted arrays, with reversal commuting definitionally. Independent consumers allow an arbitrary Function.update at the critical entry and prove equality of the entire contracted array and hence the entire actual contracted inverse. This is an array identity derived from physical positions, not an assumption that the contracted inverse or propagation response is unchanged.'},
 {'clause':'Actual contracted geometric word and root','assessment':'geometricBoundaryArray_contractedWord unfolds the true reversed-order chirotope determinant of the contractedWordTuple at local root zero. The already independently reviewed contractedWord_boundary theorem replaces each of its three actual sampled boundary points by the original boundary point at expandPosition. The resulting determinant is exactly the original geometric array composed with expandTriple, including both integer and ring casts. No G1 assumption is needed for this sample equality. The independent consumer combines it with the proved off-leaf inverse transport to identify the actual original c value with the actual cQ of that geometric contracted word, and another checks reversal on that same array.'},
 {'clause':'Formal leaf base and proper contracted polygon output','assessment':'contracted_leaf_inverse_value applies the established one-leaf inverse theorem to the proved contractedLeaf length one. This remains an open-word statement when the entire contraction has two positions; the full-contraction consumer verifies exactly that case and does not introduce a two-gon amplitude. For a proper contraction, the separately reviewed size bound supplies at least three positions and the actual contractedWord_G1 proof follows from singleton zero support. The full far-only output then equals the actual treeCoefficient of that contracted word at local root zero. The current proper-output consumer pairs this coefficient equality with the exact directed-edge equality edge(Q,0)=edge(P,g), retaining the source physical root rather than merely renaming an index.'},
 {'clause':'Unique distinguished child without loss of unary compositions','assessment':'Every complete contracted composition of a containing interval expands to a surviving original cut list and therefore has a child containing the old critical arc. The interval-containment equivalence identifies the corresponding child containing the formal distinguished leaf. The separately reviewed positive-interval child-uniqueness theorem makes it unique even though adjacent children share endpoints. The independent unary consumer retains the one-part composition and its unique child. This is a complete structural domain statement; it does not claim the changing-child induction hypothesis is already available on a unary composition.'},
 {'clause':'Conditional product response and strict induction scope','assessment':'expanded_child_product_response explicitly assumes the response only on a containing child of the current composition. The exact one-changing-factor product theorem expresses the full difference as that factor difference times all remaining baseline factors. Every other contracted child excludes the positive-length distinguished leaf, so the proved off-leaf inverse theorem, not a new assumption, identifies those other factors with cQ. Substituting the explicit child premise and reassembling the complete product with mul_prod_erase gives s times the full contracted child product, without division. The zero-factor consumer verifies the formula still gives zero when an actual contracted factor vanishes. For an eventual interval-length induction, the response premise is justified only on strictly shorter children; the independent nonunary consumer proves strict decrease for every expanded child when parts>=2. Applying this conditional lemma to a unary composition would require the response of the whole interval as input, so it cannot by itself establish propagation. The final nonunary summation and induction remain pending.'},
 {'clause':'Nonsurviving differences vanish without dropping values','assessment':'If any child of a nonsurviving composition contained the complete critical span, survivingCuts_of_containing_child would force every top cut to survive, contradicting the premise. Thus each child excludes the critical span. The established off-critical locality theorem makes every actual c factor equal on both sides, and product congruence equates the whole products. The independent consumer states exactly that their difference is zero, not that either product is zero. This supports discarding these differences only after subtraction, as required by the source propagation argument.'},
 {'clause':'Independent evidence and limits','assessment':'The fresh22 position/unique-child review, fresh10 geometric-word review, and fresh27 interval/composition review are hash-bound and their file bindings are revalidated. Their verdicts do not replace the present reading of the new19 proofs and actual types. The combined current trace compiles all ten exact frozen bodies and independently checks the new19 declarations plus19 consumers over the54-module canonical import closure. CriticalContractionPositions also has a frozen standalone prototype that was never executed; no standalone pass is claimed, and the executed18 evidence is the joint Bounds78486 receipt. No implementation, source, or map was changed. The completed source propagation theorem, its signed nonunary reindexing/induction, and the final proper-span wall formula remain outside this partial review.'}],
 'independence':'Reviewer authored only the new check consumers, preparation and evidence. No mathematical implementation, source, map, root receipt, or prior frozen review was edited. All three new bodies were frozen after successful root kernels before review consumers were written. The independently reviewed predecessor proofs are bound explicitly, while the current actual types, transparent definitions and source roles were checked directly. No auxiliary child-response premise is misrepresented as a completed induction.',
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Complete signed nonunary sum reindexing and the interval-length propagation theorem.','Final proper-span rooted response and assembly with the original wall-data domain.','The remaining corner wall laws, soft theorem, R theorem and whole stage.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash for these external helpers.','No claim that the conditional product response proves its own changing-child premise.','No two-vertex polygon amplitude, no discarded nonzero product values, and no overall stage completion.']}
out='work/reviews/off-leaf-contraction-prototype.json';write(out,d)
print(out,sha(out));print('PASS19 new declarations+19 consumers;38 standard-or-empty traces;54-module closure;327 canonical files unchanged; genuine off-leaf inverse proof and conditional product step distinguished.')
