from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/refined-weights-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256']
for key in ['root_receipts_sha256','root_files_sha256','SM_closure_files_sha256','inherited_review_binding']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
for key in ['trace','new_examples','previous_examples','factorization_examples']:assert sha(p[key])==p[key+'_sha256']
fragmentfile='work/reviews/marked-transport-independent.json';fragment=load(fragmentfile)
assert sha(fragmentfile)=='660b35e9ce99e04fce1ad1a722652b388806cdf0df55574b09804a66a9f71174'
for f,h in fragment['files_sha256'].items():assert sha(f)==h
fragments=['SM.BoundaryCutSet.marked_transport_val','SM.IntervalComposition.nestedMarkedCutEquiv_marks']
assert fragment['scope']['declarations']==fragments
for d in fragment['reviewed_declarations']:
 s=''.join((base/d['path']).read_text().splitlines(keepends=True)[d['first_line']-1:d['last_line']])
 assert s==d['text'] and sha256(s.encode()).hexdigest()==d['sha256']
logfile='work/checks/refined-weights-review-types.log';s=(base/logfile).read_text();assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==93 and len(examples)==30
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 i=m.start();j=s.index("'"+n+"'",i);types[n]=s[i:j].strip()
oldtypes=load('work/checks/refinement-transport-reviewed-types.json')['types'];assert len(oldtypes)==41
assert all(types[n]==t for n,t in oldtypes.items())
typefile='work/checks/refined-weights-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'new_checked_declarations':p['new_checked_declarations'],'all_41_predecessor_types_unchanged':True,'consumer_count':30,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/refined-weights-review-closure.json'
write(closurefile,{'status':'independent second kernel passed; five new frozen bodies reviewed','source':p['source'],'source_sha256':p['source_sha256'],
 'SM_import_roots':p['SM_import_roots'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':20,'reviewed_files_sha256':reviewed,
 'embedded_frozen_bodies':{n:sha('work/checks/'+n+'.body.lean') for n in p['body_order']},'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],
 'fresh_fragment_review':fragmentfile,'fresh_fragment_review_sha256':sha(fragmentfile),'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),
 'scope':'Full actual coefficient/child summand transport, full polynomial-map factorization, all solution-level far-only output and geometric full-root/leaf/nonleaf values. Restricted nonleaf word/closing-root identification is absent; no original source acceptance.'})
roots={}
for n in p['body_order']:
 f='work/checks/'+n+'-prototype-result.json';roots[n]=dict(load(f),receipt=f,receipt_sha256=sha(f))
old=load('work/reviews/def-nearfar.json')
prior={'session':28998,'exit_code':1,'source':'work/checks/refined-weights-review-first.lean','log':'work/checks/refined-weights-review-first.log',
 'reason':'The reviewer factor-count consumer omitted parentheses around per-child subtraction inside a finite sum. Lean parsed subtraction outside the sum, changing the intended statement. Explicit parentheses corrected this reviewer statement; all implementation traces already passed. No implementation/source statement was changed.'}
prior['source_sha256']=sha(prior['source']);prior['log_sha256']=sha(prior['log'])
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),
 'independent_kernel_command':'lake env lean ../checks/refined-weights-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':False,'prior_failed_independent_run':prior,
 'checked_declarations':names,'declaration_count':93,'new_declaration_count':52,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':30,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},
 'all_41_predecessor_types_unchanged':True,'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),
 'root_successful_results':roots,'fresh_fragment_statement_review':fragmentfile,'fresh_fragment_statement_review_sha256':sha(fragmentfile),
 'scope_note':'The independent trace compiles the exact nine frozen bodies over the actual 20-module canonical dependency closure and tests 30 substantive consumers. The fresh fragment reviewer supplies authorship-independent source review of two reused cast/marking fragments; this kernel supplies fresh elaborated types and axiom traces for them as well.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'nearfar-factorization-far-only-prototype','source_id':'lem:farout','source_line':146,
 'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':'Lemma146-168 and proof170-227. Full factorization151 and proof180-199, complete far-only/geometric output153-158 and201-211, ordinary nonleaf and both leaf values159-162. Restricted nonleaf word/closing-edge-root coefficient163-165 and213-226 remains incomplete.',
 'additional_source_sha256':old['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910',
 'verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,
 'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':p['new_checked_declarations'],'main_declarations_by_body':{n:p['checked_declarations_by_body'][n] for n in p['new_body_names']},
 'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['new_body_names']},'reviewed_files_sha256':reviewed,'import_closure_roots':p['SM_import_roots'],'import_closure_file_count':20,'embedded_body_count':9,
 'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':old['pins'],
 'reason':f'Faithful complete factorization and far-only output development within the explicit partial source scope. Every inner near factor and marked outer far factor is matched using actual physical triples; every child factor is retained. The actual full raw nested/marked equivalence preserves complete summands, and summing all marks yields Phi=F composed with G on all interval arrays over every allowed commutative ring. The whole reversed-far output of any solution depends only on H and its target; the geometric full-root coefficient and the source leaf/nonleaf values follow. Independent second kernel {session} passes 93 declarations and 30 consumers with 123 standard-or-empty axiom traces. Two marking-transport fragments reuse an earlier reviewer argument; their fresh, noncontributing reviewer report is hash-bound here. Full lem:farout remains incomplete because the restricted nonleaf word and its closing-edge-root coefficient are not yet identified.',
 'mathematical_justification':[
 {'clause':'Actual unmarked fine cuts and all inner cuts','assessment':'RefinementUnmarked is every fine interior index whose actual physical position is absent from the outer cut set. Each inner interior cut lies strictly inside its outer part, lies in the global refined cut set by restriction, and cannot be an outer cut because the part is consecutive. The actual fine index is recovered by the physical-position equivalence. Equality of images forces equality of strict outer-part interiors and then inner indices. Conversely an unmarked fine cut lies in a half-open outer part; it cannot equal that part’s left endpoint because that would be an outer cut, so it is strictly interior and occurs in the exact recovered inner composition. Thus all and only unmarked cuts occur once, including empty unary domains.'},
 {'clause':'Exact inner neighboring triples','assessment':'For each inner cut, the preceding and following child intervals are globally consecutive in the refined cut set. The existing consecutive-triple uniqueness theorem therefore identifies both neighbors around the same physical middle cut. inner_nearTriple_transport proves equality of the full triples, not merely equality of their signs or scalar samples. Applying any triple-valued factor function and reindexing the full sigma of inner interior indices gives the exact unmarked fine product. The independent entry consumer checks all three positions explicitly.'},
 {'clause':'All marked cuts and global far endpoints','assessment':'Every outer interior position remains a refined interior position by cut-set containment. The position-preserving outer-index map is injective; any marked fine interior position is an actual outer cut strictly between the global endpoints, so it has a unique outer interior index. RefinementMarked therefore contains exactly these positions. Both farTriple constructions use the same source interval I; their lower and upper entries are I.left and I.right, and their middle entries agree by the position lemma. The independent consumer checks those exact global endpoints, excluding an accidental inner-interval far sample. Reindexing arbitrary far-triple factors supplies precisely every marked factor.'},
 {'clause':'Exact partition and half coefficients','assessment':'refinementMarks stores the actual outer interior positions as marks of the fine composition. refinementMarkIndices recovers their fine indices; membership is equivalent to membership in the outer cut set because all fine indices already exclude global endpoints. Subtype products therefore equal products over this exact finite marked set and its complementary interior-index set. The independent factor-count consumer combines both index equivalences and the subtype-complement cardinality formula to show that the outer interior count plus every inner interior count equals the fine interior count. Thus every refined interior cut supplies exactly one half factor. Near-only weights become D of the actual neighboring triple times inverse two; far-only weights become negative H of the global-endpoint triple times inverse two.'},
 {'clause':'Complete recovered and arbitrary raw nested summands','assessment':'nested_summand_transport distributes the product of each inner weight times its child product. The proved near-factor product, marked far-factor product and full refined child-coordinate product then yield exactly the source marked/unmarked coefficient times the complete refined child product. The ring is arbitrary CommRing with invertible two; no field, ordering or nontriviality premise appears. Independent raw-family consumers replace every recovered inner composition by the original arbitrary family using refinementInner_flatten and whole-family congruence, so coverage does not depend on a restricted reconstructed-family presentation. Unary outer data gives no marks; an identical outer/fine cut set marks every fine position; every unary inner coefficient is one.'},
 {'clause':'Actual marked equivalence and disclosed shared proof provenance','assessment':'nestedMarkedCutEquiv_marks projects the actual full canonical nested/marked equivalence and proves that its physical marked finset is exactly the original outer interior finset. Its final inverse sigma equivalence transports a dependent marking along equality of the reconstructed and original cut sets; marked_transport_val proves this leaves the underlying positions unchanged. These two fragments adapt the earlier independent consumer argument and are not treated as authorship-independent work of this reviewer. A separate reviewer, /root/review_mark_transport, independently read their exact source, proofs, canonical map and mathlib transport definitions, with no authorship. Its passed report and exact fragment hashes are bound here; the current kernel independently checks their elaborated types and standard axiom traces.'},
 {'clause':'Termwise correspondence through the actual full source bijection','assessment':'nestedSummand and markedSummand are transparent products of the actual outer far weight, all inner near weights, all child coordinates, and the corresponding selected/complementary fine factors. The marking projection identifies the output marking with refinementMarks, while exact raw-family recovery identifies the original inner family with the restriction family. The proved complete-summand transport then gives equality under nestedMarkedCutEquiv for every actual raw outer composition and every inner family. Neither the bijection nor the factor equality is assumed as a premise.'},
 {'clause':'Full factorization on all interval arrays','assessment':'nearFar_factorization_coordinate expands the actual F_H(G_D(X)) definition by finite distributivity over every inner composition choice for every outer part. The double sum is rewritten as its complete sigma index domain. Fintype.sum_equiv reindexes that sum through the exact source nestedMarkedCutEquiv using the proved equality of complete summands. The resulting sigma sum separates into every refined composition and every physical mark set. The marked-index equivalence rewrites the inner sum over all index subsets; nearFarWeight_marked_expansion recombines the negative-far and near half choices independently. The result is exactly the defining Phi sum, and function extensionality yields Phi=F_H composed with G_D on the whole array space. An independent inverse-order consumer derives G_D inverse after F_H inverse, confirming the composition order. The unary marked-sum consumer retains precisely X_I.'},
 {'clause':'Polynomial inverse premise already supplied without new axioms','assessment':'The existing canonical triangular-polynomial development supplies explicit coordinate polynomials for the inverse of every exact Phi and both inverse identities; its full source and canonical review is already bound through the inherited NearFar dependencies. This batch’s factorization operates on the actual finite polynomial expressions, without an additional literature axiom or a new bijectivity premise. The independent inverse-order and canonical-solution consumers use those proved inverse identities on arbitrary targets.'},
 {'clause':'Whole-solution far-only output and genuine near-array independence','assessment':'If Phi(D,H)(X)=Y, full factorization gives F_H(G_D(X))=Y. Applying the proved uniqueness of the F_H inverse identifies the entire near-only array G_D(X) with nearFarInverse(0,H)(Y). Factorization with negative H then identifies the complete reversed-far output with F_(-H) of that same array. Thus two independently chosen near arrays and their possibly different solutions at a common target have identical complete output. The independent consumer instantiates both solutions with their actual constructed inverses, so no hypothetical existence premise is required. No independence of individual tree terms or open sums is asserted.'},
 {'clause':'Exact geometric source root and representative transport','assessment':'farOnlyCoordinates is precisely nearFarInverse(0,H)(E), and farOnlyOutput is F_(-H) of that coordinate array. The previously proved actual geometric open sums solve Phi(b)=E; substituting them gives the full geometric far-only array. The actual rooted tree coefficient is its fullBoundaryInterval coordinate using the source root theorem and hn:3<=n. An independent consumer combines this with solution-level independence to express the same geometric root coefficient using any arbitrary near array D and its actual inverse solution. Another consumer applies the proven simultaneous tuple/root shift to the entire far-only output, preserving the specified physical root.'},
 {'clause':'Source leaf and nonleaf coordinate conventions','assessment':'On a one-leaf interval there is no nonunary raw composition, so every Phi is the identity on that coordinate. The source E indicator is one there; the inverse equation forces c to be one, and both F_H(c) and F_(-H)(c) are one. On any interval with at least two leaves, the actual inverse equation F_H(c)=E gives the ordinary coordinate zero. These statements quantify over every source interval and arbitrary allowed H. They implement the open-word convention only; no two-vertex polygon amplitude is introduced.'},
 {'clause':'Remaining original source clause','assessment':'The new types do not construct an independently indexed restricted word, prove the coordinate/composition/array restriction equivalences, or identify its far-only coordinates with the restriction of the original c. They also do not identify the nonleaf restricted word’s tree coefficient at the actual closing edge from a_j to a_i. The whole-source statement in lines163-165 therefore remains unproved by this batch, even though its numeric leaf/nonleaf clauses and the full factorization/far-only output are established. Later untested IntervalRestriction work is outside these exact frozen files.'}],
 'independence':'This reviewer independently inspected the full source, five new bodies, predecessor definitions and proof constructions, and authored consumer checks. The two explicitly listed marking-transport fragments adapt an earlier argument by this reviewer; no unqualified claim of authorship independence is made for them. Their exact statements/proofs received the separately hash-bound fresh review by /root/review_mark_transport, who contributed to neither fragment nor earlier consumer. Only new reviewer evidence files were written; no implementation, source, map, root receipt or frozen prior review was edited.',
 'provenance_disclosure':{'reviewer_derived_fragments':fragments,'origin_consumer':'NearFarRefinementIndependentReview.marked_forward_has_actual_cuts','origin_file':'work/checks/nearfar-refinement-review-examples.lean','origin_file_sha256':sha('work/checks/nearfar-refinement-review-examples.lean'),'fresh_noncontributing_reviewer':fragment['reviewer'],'fresh_fragment_review':fragmentfile,'fresh_fragment_review_sha256':sha(fragmentfile),'fresh_review_is_read_only_without_its_own_kernel':True,'current_independent_kernel_checks_fragments':True,'scope_resolved_by_combined_reviews':True},
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_and_current_semantic_audit_pending':True,'full_farout_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Restriction compatibility for the independently indexed nonleaf boundary word and its inverse coordinate array.','Identification of its tree coefficient at the specified closing edge from a_j to a_i.'],
 'not_certified':['No whole original lem:farout acceptance before its remaining restricted-word clause and exact canonical audit/review.','No wall law, soft theorem, R theorem or stage completion.','Later IntervalRestriction prototypes are outside this frozen review.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/nearfar-factorization-far-only-prototype.json';write(out,d);print(out,sha(out));print('PASS:93 declarations+30 consumers,123 standard-or-empty traces;52 new declarations;41 predecessor types unchanged; full factorization/far-only scope with restricted-word clause outstanding.')
