from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/critical-cut-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256'] and sha(p['trace'])==p['trace_sha256'] and sha(p['examples'])==p['examples_sha256']
for key in ['SM_closure_files_sha256','root_files_sha256','root_receipts_sha256','inherited_review_binding']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
roots={f:load(f) for f in p['root_receipts_sha256']};assert all(r['exit_code']==0 for r in roots.values())
logfile='work/checks/critical-cut-review-types.log';s=(base/logfile).read_text();assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==21 and len(examples)==13
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
typefile='work/checks/critical-cut-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'additional_examples':examples,'consumer_count':13,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/critical-cut-review-closure.json'
write(closurefile,{'source':p['source'],'source_sha256':p['source_sha256'],'source_id':'thm:single-triple','SM_import_roots':['SM.Farout'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':32,'reviewed_files_sha256':reviewed,'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),'scope':p['scope']})
prior=load('work/reviews/lem-farout.json');failed=dict(p['prior_failed_independent_run'])
failed['source_sha256']=sha(failed['source']);failed['log_sha256']=sha(failed['log'])
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),'independent_kernel_command':'lake env lean ../checks/critical-cut-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':False,'prior_failed_independent_run':failed,'checked_declarations':names,'declaration_count':21,'root_printed_declaration_count':19,'additional_transparent_domain_count':2,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':13,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),'root_successful_results':roots,'root_receipts_sha256':p['root_receipts_sha256'],'scope_note':'Two exact frozen external bodies over the actual 32-module canonical Farout closure. All 19 root-printed declarations and both middle-domain aliases receive full printed types and axiom traces; 13 substantive consumers check actual domains, sums, occurrence and signs.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'critical-cut-split-occurrence-prototype','source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910','verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':names,'main_declarations_by_body':p['checked_declarations_by_body'],'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},'reviewed_files_sha256':reviewed,'import_closure_roots':['SM.Farout'],'import_closure_file_count':32,'embedded_body_count':2,'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':prior['pins'],
 'reason':f'Faithful exact splitting and critical far-gate steps within the partial proof of thm:single-triple. The complete raw middle-cut composition domain is bijective with every pair of actual gap compositions, including unary gaps, through the existing exact cut-set representation and explicit closed-gap filters/union. Arbitrary sums are reindexed by this proved bijection. An actual far triple is critical exactly at its full span with middle cut, and then occurs once. Coefficients elsewhere or without the middle cut remain unchanged. Removing that unique factor gives ordinary negative-delta and reversed positive-delta formulas with all other factors retained. Independent second kernel {session} checks 21 declarations and 13 consumers with 34 standard-or-empty traces. The first reviewer run failed only a consumer proof and is preserved. Full gap child/gate product transport, wall geometry, jumps and propagation remain outside these files; no original wall theorem is accepted.',
 'mathematical_justification':[
 {'clause':'Exact positive critical span and raw domains','assessment':'spanInterval has the actual lower and upper positions of an increasing triple x<y<z; both gaps [x,y] and [y,z] are strictly positive-length intervals. MiddleCutSet is exactly every bounded endpoint-containing cut set of [x,z] that also contains y. MiddleComposition is exactly every original raw IntervalComposition of [x,z] whose actual cut set contains y. No fixed arity, nonunary domain restriction or extra gap-length lower bound is imposed. The existing composition/cut-set equivalence preserves all cut positions and recovers the full raw structure, with finite arity derived from strict ordering.'},
 {'clause':'Physical splitting and joining with one shared endpoint','assessment':'joinGapCuts takes the union of both actual gap cut sets. Their left/right endpoint membership and interval bounds imply this is a valid whole-span cut set containing y. splitGapCuts restricts to both closed gap intervals using literal position filters. In split after join, a cut imported from the wrong gap can lie in the other closed gap only if it is y, and y is already an endpoint of that gap. In join after split, each whole-span cut lies on at least one side of y by total order; neither filter introduces a new cut. Extensionality therefore proves both full inverse laws. An independent consumer proves that the intersection of the two original cut sets is exactly the singleton {y}, establishing that the shared position appears once in the joined finite ordered list.'},
 {'clause':'Full raw composition equivalence and all pair coverage','assessment':'gapCompositionEquiv composes the exact whole-span raw composition/cut-set equivalence, the proved physical gap-cut equivalence, and both inverse gap composition/cut-set equivalences. Its range is the entire Cartesian product of all left and right raw compositions. Explicit left/right cut lemmas expose the two closed-interval filters; the inverse cut lemma exposes the literal union. Since the sorted cut-set representation is proved equivalent to the unchanged raw composition type, this identifies actual ordered cut lists and their arities, not only abstract cardinalities. Independent consumers check the exact union membership of every physical position, both separate unary-gap roundtrips with the other gap arbitrary, and full finite cardinality of the Cartesian-product domain.'},
 {'clause':'Arbitrary complete-sum reindexing','assessment':'sum_middle_compositions uses Fintype.sum_equiv with the actual proved gapCompositionEquiv; the summand equality is the exact inverse law. The resulting product-type sum is expanded into a sum over every left composition and every right composition. The summand is arbitrary and only AddCommMonoid is required, so no wall-response identity, coefficient transport or factorization is assumed. An independent consumer applies this to an arbitrary function of both actual split components and simplifies the inverse-forward laws, yielding precisely the full double gap sum. This is the source index bijection, not yet a proof that the original weighted child product becomes a product of gap contributions.'},
 {'clause':'Exact far-triple occurrence and uniqueness','assessment':'By definition a farTriple reads the current coordinate interval endpoints and its actual interior cut. Equality to the critical triple therefore implies that the coordinate interval equals [x,z] and the actual interiorPosition equals y; conversely these equalities imply equality of all three triple entries. The interior-position map is injective by strict cut ordering, hence the far-triple map is injective. Existence of the critical far triple is equivalent to whole-span equality and actual middle-cut membership: the strict x<y<z bounds ensure middle membership is interior membership, and the existing exact interior-index equivalence supplies its unique index. The independent middle-composition consumer also derives parts>=2, so the existential index is nonvacuous and the unary composition cannot accidentally contain an interior critical gate.'},
 {'clause':'Other coordinates versus off-span inverse locality','assessment':'If the current coordinate differs from [x,z], every one of its far triples differs from the critical triple, even if the coordinate strictly contains [x,z]. Equality of all noncritical array entries therefore preserves its entire far coefficient product. Likewise a composition without the middle cut cannot contain the critical far triple, so its coefficient is unchanged. Independent no-occurrence consumers verify both conditions directly, and a paired consumer checks ordinary and reversed coefficients without the middle cut. This is correctly distinct from c locality: coefficients of a larger coordinate are unchanged while its child inverse coordinates may change. No erroneous claim of unchanged c on every coordinate other than [x,z] is made.'},
 {'clause':'Ordinary one-gate difference with arbitrary ring scalars','assessment':'For a selected index k whose actual far triple is critical, injectivity shows that every j different from k samples a noncritical triple. All factors in the product over univ.erase k are consequently equal between H1 and H2. The proof separates the k factor from each complete finite product by mul_prod_erase, rewrites the common remaining product, and distributes the subtraction. The changed factor is -(H2(t)-H1(t))*inverse(2), so the result is negative delta times the complete product of remaining negative far factors. This uses arbitrary CommRing with invertible two; no field, ordering, nonzero scalar or geometric sign premise is added. Exactly-once occurrence describes the varying input gate, not a claim that the numerical product difference is nonzero for arbitrary ring arrays.'},
 {'clause':'Separate reversed-far sign and retained reversed factors','assessment':'The reversed coefficient theorem applies the ordinary difference calculation to the arrays -H1 and -H2 and explicitly simplifies the negations. Its critical multiplier is +(H2(t)-H1(t))*inverse(2), and every remaining factor is +H1 of its actual far triple times inverse two. Thus both the changing sign and all retained signs are reversed, as required in source313-317. The independent general-delta consumer introduces an arbitrary scalar delta equal to this half difference and verifies both complete formulas. The binary consumer proves the erased index set is empty when parts=2, reducing the differences to precisely -delta and +delta; this also checks empty products are one.'},
 {'clause':'Unary and boundary cases are retained','assessment':'Either gap may be unary and is explicitly included in the raw product range. The whole-span unary composition has no interior far index and its nearFarWeight is one for both H and -H; an independent consumer checks both values without an array agreement premise. A middle-cut composition has at least two parts by existence of its interior index. The binary case leaves no remaining factors after removing its critical gate. These facts cover the source empty-product and minimal-composition conventions without imposing extra positivity or geometric assumptions.'},
 {'clause':'Precise remaining proof scope','assessment':'The two bodies implement source281-289 occurrence and cut-list splitting, together with ordinary/reversed single-gate scalar differences used in source313-317. They do not yet identify the complete product of joined child coordinates with the two gap products, nor transport all remaining far gate samples to actual gap gates with epsilon signs. The wall-germ common-shrink sign comparison, gap G1, epsilon identities, critical c jump, contracted polygon and larger-interval propagation formulas remain unproved by this batch. The later draft GapSplitProducts is explicitly excluded. The complete thm:single-triple and final corner wall laws therefore remain unaccepted.'}],
 'independence':'The reviewer independently read the authoritative source, both exact frozen bodies, actual canonical cut/composition/array definitions and proof constructions, and wrote only new reviewer consumers and reports. No implementation, source, map, root receipt or frozen prior report was edited. The first consumer failure was preserved and corrected only in its proof. These two implementation bodies contain no reviewer-authored fragment. Earlier Farout marking-fragment provenance remains disclosed through the bound accepted source review and fresh noncontributing fragment review.',
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Complete joined child-coordinate and epsilon-weighted gap-factor product transport.','Wall-germ sign stability, nondegenerate gap geometry and epsilon identities.','Critical-coordinate c and reversed-output jump formulas.','Contraction and larger-interval propagation.','Both final single-triple wall-response formulas.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash.','Later untested GapSplitProducts is outside this frozen review.','No complete corner wall law, soft theorem, R theorem or overall stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/critical-cut-split-occurrence-prototype.json';write(out,d);print(out,sha(out));print('PASS:21 declarations+13 consumers;34 standard-or-empty traces; exact split/occurrence/delta scope only; no original acceptance.')
