from pathlib import Path
from hashlib import sha256
import json,re,datetime
base=Path(__file__).resolve().parents[2]
def sha(rel):return sha256((base/rel).read_bytes()).hexdigest()
closure=json.loads((base/'work/checks/relative-general-position-review-closure.json').read_text())
trace=(base/'work/checks/relative-general-position-review-types.lean').read_text()
log=(base/'work/checks/relative-general-position-review-types.log').read_text()
assert not re.search(r'error[:(]',log)
names=re.findall(r'^#check (\S+)',trace,re.M)
examples=re.findall(r'^theorem (\w+)',(base/'work/checks/relative-general-position-review-examples.lean').read_text(),re.M)
axioms={}
for n in names+['RelgpIndependentReview.'+x for x in examples]:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",log)
 if m: axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in log,n
  axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'}
types={}
for n in names:
 start=log.index(n+' ');end=log.index("'"+n+"'",start)
 types[n]=log[start:end].strip()
(base/'work/checks/relative-general-position-reviewed-types.json').write_text(json.dumps({'format':'pp.fullNames true, pp.universes false; #check output before corresponding #print axioms','types':types,'printed_type_sha256':{n:sha256(s.encode()).hexdigest() for n,s in types.items()}},indent=2)+'\n')
reason='The complete source conclusion is faithfully derived from only the ambient n>=3, a continuous labelled Regular curve, Generic endpoints, and delta>0. The proof constructs one actual finite piecewise-affine path and then classifies every actual nongeneric parameter of that same path. Its exact labelled endpoints, synchronous Euclidean closeness, Regular membership, physical vertex injectivity, nonzero labelled edges, Generic collars, finite isolated nongeneric parameters, actual shifted-path germs, exactly one of F/V-bigon/V-sliding/T/E/C, and absence of all cusps are explicit output properties. The stronger construction retains the same event control, fine-cell/time, smooth ambient graph and nonzero actual-time derivative rather than assuming transversality. Independent source/definition/proof inspection plus seven kernel-checked consumer theorems verify these meanings; neither successful compilation nor inherited verdicts alone establishes this fidelity. This is a full-source prototype fidelity verdict. Canonical port, canonical semantic dependency hash and whole-project candidate/acceptance audit remain required before mapping the original claim as accepted.'
clauses=[
 ('Exact source inputs and representation','The source conventions impose n>=3 globally and use actual occurrence indices modulo n. LabelledTuple is ZMod n -> Real x Real; all tuples and edge occurrences remain in this same type throughout. Generic is the conjunction of actual point determinant nonvanishing and absence of actual triple interior concurrence. Regular is equivalent to every actual edge being nonzero and not a negative multiple of its preceding edge; positive collinear turns remain allowed. Continuous gamma with pointwise Regular is the subtype-free presentation of a continuous path into the Regular locus. NeZero n is derived from n>=3 in the independent raw-source examples and is not an extra restriction. No injectivity, polynomial endpoint avoidance, waypoint, root, classification or derivative hypothesis is added.'),
 ('One genuine finite piecewise-affine approximation','The construction uses one CurveCubeSubdivision, one common internal assignment W and one CubeCoordinateApproximation A. The fine mesh has d.count*(2*n)>0 cells, with endpoints j/N in the actual source time interval. uniformMeshPoint_strictMono proves strictness, uniformMeshCell is the actual closed interval between consecutive endpoints, and iUnion_uniformMeshCell proves complete coverage. Distinct cells intersect only in a shared adjacent endpoint by the inherited proved intersection lemma. The output affine formula is a z+t*b z on every coordinate of every point in each cell. The independent actual_labelled_piecewise_affinity theorem converts those scalar formulas to actual plane-valued labelled vertex formulas without an extra premise. Thus the record does not merely assume a finite cover of arbitrary patches or reparameterized affinity.'),
 ('Exact endpoints, physical labels, regularity and collision freedom','The path is actual ZMod n-indexed tuples at every time. first and last are tuple equalities with gamma(0),gamma(1), from which independent checks derive equality for every occurrence label. A.regular holds on every glued cell including boundaries. collision_free is Function.Injective at every actual time, not only at Generic times. The actual labelled edge nonzero field follows from RegularPair, keeping every occurrence available without quotienting, renumbering or deleting a label. Source collisions along gamma are not prohibited; injectivity is a proved property of the approximation.'),
 ('Synchronous true Euclidean uniform error','tupleCoordinates is the explicit 2n-coordinate EuclideanSpace representation, with a proved inverse and compatible topology. The close field compares A.path(t) and gamma(t) at the same actual time using this Euclidean metric. The construction places both in the same coarse cube after fine-to-coarse time-cell inclusion, and applies that cube actual pairwise distance bound. No default product maximum metric or unrelated reparameterization substitutes for this error. The independent uniform_margin theorem applies the extreme value theorem to the continuous distance between the two actual paths on compact unitInterval and returns one m<delta with every error<=m. This verifies the usual strict uniform interpretation even though the record presents pointwise strict inequalities.'),
 ('Actual events, fixed endpoints and genuine shifted germs','Generic first/last cubes give a positive Generic endpoint collar and do not require inactive concurrence controls to be nonzero there. Actual nongeneric times lie in strict central fine-cell interiors. Finite_nongeneric is the actual set of nongeneric global parameters, obtained as a subset of finitely many roots; it is not an equality declaring every inactive supporting-line T root a wall. E.germ_center is A.path(t), while curve_on_path equates the entire germ curve at s with this same A.path(t+s) and proves that actual shifted time lies in [0,1]. The WallGerm is continuous, has a genuinely nongeneric centre and all punctured parameters Generic. isolates_shifted_path uses s=u-t and that exact equality to obtain a positive isolation radius; the independent actual_events consumer extracts all those clauses solely from the output record.'),
 ('Exhaustive F, V-bigon, V-sliding, E and C branches','The point-control centre proof equates the actual complete point-zero set with the selected unordered three-element support and excludes all actual interior-concurrence triples. Support decomposition considers actual cyclic adjacency: no adjacent pair, a consecutive turn support, or a contact-separated adjacent pair and third vertex. The n=3 regular collinear case is excluded by the proved closed-triangle obstruction, not dropped. At a consecutive support, collision freedom excludes endpoints and an exterior middle point would force the forbidden negative edge multiple, leaving strict betweenness. A separated contact is proved on the actual supporting line and is either in the actual finite edge interior or outside its closed segment. Named determinant sign changes are transported through exact representative-or-negative polynomial identities and through the real sign function, completing the full existing wall predicates. The V split uses equality/inequality of the actual two neighbour chirotopes; their nonzero heights are separately proved. No centre-only classification is silently promoted to a simple wall.'),
 ('Active T branch and actual crossing-order changes','The edge-control centre proof uses actual nongenericness together with empty point zeros to derive a genuine remote triple interior concurrence. Its supporting polynomial must be the unique zero control, hence the full actual concurrence set is that singleton. Inactive generic T roots are not classified. At the active centre actual G1 and common interiors give nonzero pair determinants. The expanded 3x3 determinant identity has the source minus sign T=-(t_ef-t_eg)*H_ef*H_eg, where the parameters are the actual directed Cramer ratios. The proved continuous nonzero-factor lemma gives a common positive neighbourhood and preserves negative opposite-side products. Permuting the same representative gives all three required order changes in the exact TripleAt predicate. The inherited actual triple-sides theorem supplies persistent interior crossings, and crossingParameter_eq_edgeParameter identifies those source parameters with the ratios used by TripleAt.'),
 ('Exactly one of six kinds, with different proposed marks handled','RegularWallKind contains precisely flat, bigon, sliding, triple, extension, cut. HasRegularWallKind transparently existentially quantifies the exact existing FlatAt, BigonAt, SlidingAt, TripleAt, ExtensionAt and PureCutAt predicates. The point and active-T results derive E.simple, after which no-cusp converts the older six-kind taxonomy containing cusp and unsplit vertex to the requested taxonomy. Existing centre separation handles unequal underlying kinds. For bigon versus sliding, equal singleton point-zero sets force equal contact supports, and contactSupport_marks_unique forces the same actual M,a even if the two proposed witnesses had different marks. Actual neighbour-sign equality and inequality then contradict. The independent cross_mark_subtype_exclusion theorem checks this stronger cross-witness case. Uniqueness concerns the type, as in the source, not uniqueness of an arbitrary ordered representation of an unordered triple.'),
 ('Transversality refers to the same actual classified event','TimedEventCertificate binds the root polynomial, chosen coordinate, centre, fine cell, actual leg curve, actual shifted global path, sign change, evaluated nonzero slope, nonzero global-time derivative and C-infinity graph. Its derivative scalar is the actual affine leg parameter slope multiplied by the positive fine-cell speed d.count*(2*n). The independent raw_source_transverse_events theorem first obtains one A from the raw source premises, then for every actual nongeneric time obtains the same classified E and a real scalar function F with HasDerivAt F v 0, v!=0, whose values equal the named polynomial on A.path(t+s) for every s in that same E.germ. Thus the retained derivative is attached to the actual path and the same control, rather than a disjoint witness. The graph domain is the open evaluated-nonzero-slope set; the root function is -intercept/slope. Actual zero-set/graph equality and the smooth injective graph with its actual projection inverse yield a concrete smooth hypersurface near that same centre. event_on_actual_smooth_graph checks those fields and the centre membership. The flat final record retains source SignChanges/Simple; the stronger companion theorem retains the additional derivative and graph construction. No separate manifold API predicate is claimed.'),
 ('No cusp and no hidden conclusion premise','The no_cusp field quantifies every WallGerm centred at any actual path time, not only the chosen event germ. CuspAt entails an actual negative consecutive edge multiple at its centre; A.regular excludes it. All helper premises, including JointLegConditions, control nonvanishing, actual active concurrence and Simple, are supplied by already proved construction stages inside relative_general_position_with_certificates or E methods, not added to the original theorem inputs. The final relative_general_position merely assembles those derived properties for the same A. Only standard Lean axioms occur in the independent checks; no literature interfaces, sorry, native_decide or custom axioms are used.'),
]
d={
'review_schema':'independent-full-source-prototype-review-v1','id':'relative-general-position-prototype','source_id':'thm:relgp','reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910','verdict':'faithful','implemented_scope_verdict':'faithful','source_claim_accepted':False,'statement_sha256':None,'source':'reference/SM/sm-1-polygons.tex','source_lines':'1385-1539; defining conventions 13-60 and wall/germ predicates 655-750','source_sha256':closure['source_sha256'],'parameters_reviewed':True,'definition_equivalence_reviewed':True,'in_theorem_library':False,'reason':reason,'mathematical_justification':[{'clause':a,'assessment':b} for a,b in clauses],
'independence':'This reviewer did not author or edit implementation, sources, declaration maps, predecessor reviews or canonical library files. Only independent check examples, trace/closure evidence and this new review were written. Inherited reviews were inspected as supporting evidence; the full source statement, output/input definitions and assembly/point/T proof bodies were independently inspected.','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
'prototype_file':'work/checks/RelativeGeneralPosition.prototype.lean','prototype_sha256':sha('work/checks/RelativeGeneralPosition.prototype.lean'),'prototype_body':'work/checks/RelativeGeneralPosition.body.lean','prototype_body_sha256':sha('work/checks/RelativeGeneralPosition.body.lean'),'kinds_body':'work/checks/RegularWallKinds.body.lean','kinds_body_sha256':sha('work/checks/RegularWallKinds.body.lean'),'main_declarations':['SM.relative_general_position','SM.relative_general_position_with_certificates','SM.RelativeGeneralPositionPath','SM.CurveCubeSubdivision.TimedEventCertificate.regular_kind_unique'],
'pins':{'lean_toolchain':(base/'work/lean/lean-toolchain').read_text().strip(),'mathlib_revision':'85e3a25e006c35636f0e53b0e9296caca2685bc0','pin_files_sha256':closure['pin_files_sha256'],'additional_library_file_read_sha256':{'Mathlib/Topology/Order/Compact.lean':sha('work/lean/.lake/packages/mathlib/Mathlib/Topology/Order/Compact.lean')}},
'reviewed_files_sha256':closure['SM_closure_files_sha256'],'import_closure_roots':closure['root_imports'],'import_closure_file_count':closure['SM_closure_count'],'external_inputs_sha256':closure['external_inputs_sha256'],'inherited_review_binding':closure['inherited_review_hashes'],
'evidence':{'independent_trace_source':'work/checks/relative-general-position-review-types.lean','independent_trace_source_sha256':sha('work/checks/relative-general-position-review-types.lean'),'independent_trace_log':'work/checks/relative-general-position-review-types.log','independent_trace_log_sha256':sha('work/checks/relative-general-position-review-types.log'),'independent_kernel_command':'lake env lean ../checks/relative-general-position-review-types.lean','independent_kernel_session':68950,'independent_kernel_exit_code':0,'first_independent_run_passed':True,'checked_declarations':names,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':['RelgpIndependentReview.'+x for x in examples],'additional_example_count':len(examples),'additional_examples_passed':True,'additional_example_axioms':{n:a for n,a in axioms.items() if n.startswith('RelgpIndependentReview.')},'independent_examples_source':'work/checks/relative-general-position-review-examples.lean','independent_examples_source_sha256':sha('work/checks/relative-general-position-review-examples.lean'),'independent_closure_evidence':'work/checks/relative-general-position-review-closure.json','independent_closure_evidence_sha256':sha('work/checks/relative-general-position-review-closure.json'),'printed_type_evidence':'work/checks/relative-general-position-reviewed-types.json','printed_type_evidence_sha256':sha('work/checks/relative-general-position-reviewed-types.json'),'printed_types_scope':'Explicit prototype #check representations, not the canonical acceptance semantic-dependency hash. The latter is pending the canonical audit.','successful_build_session':18949,'successful_build_exit_code':0,'successful_build_log':'work/checks/relative-general-position-prototype.log','successful_build_log_sha256':sha('work/checks/relative-general-position-prototype.log'),'root_result_file':'work/checks/relative-general-position-prototype-result.json','root_result_sha256':sha('work/checks/relative-general-position-prototype-result.json'),'exact_prototype_definition_and_proof_prefix_copied_unchanged':True,'transparent_predicates_printed':['SM.RelativeGeneralPositionPath','SM.WallGerm.HasRegularWallKind','SM.CurveCubeSubdivision.TimedEventCertificate'],'non_failing_trace_warnings':'Inherited style warnings and reviewer letI proof style warnings only; no errors.'},
'audit_context':{'prior_receipt':'work/checks/checkpoint-057-output.json','prior_receipt_sha256':sha('work/checks/checkpoint-057-output.json'),'scope':'Prior canonical audit057 is supporting historical evidence only. This full prototype has independent successful kernel68950 and the exact124 imported SM file closure; all280 canonical modules matched the frozen preparation inventory before new ports. No new whole-project audit or canonical declaration hash is asserted here.','current_SM_modules_at_review':280,'all_280_prior_SM_files_unchanged':True},
'accounting':{'original_source_claims_accepted':0,'original_proof_count_increment':0,'original_checklist_increment':0,'full_thm_relgp_prototype_fidelity':True,'canonical_claim_acceptance_pending':True,'stage_completed':False},
'not_certified':['This prototype report does not itself accept the original claim in the declaration map; exact canonical port, independent canonical type/closure binding and successful current whole-project audit are required.','No main corner-state-sum wall law, soft theorem or unconditional R theorem is accepted by this report.','The output theorem is existential; no executable waypoint selection algorithm or computational numerical complexity bound is claimed.','Smooth hypersurface geometry is expressed by proved explicit open smooth graph, inverse and actual derivative data; a separate manifold API transversality predicate is not claimed.']}
(base/'work/reviews/relative-general-position-prototype.json').write_text(json.dumps(d,indent=2)+'\n')
print('Wrote faithful full prototype review; original acceptance pending. SHA',sha('work/reviews/relative-general-position-prototype.json'),'declarations',len(names),'examples',len(examples))
