from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/far-only-locality-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256'] and sha(p['trace'])==p['trace_sha256'] and sha(p['examples'])==p['examples_sha256']
assert sha(p['root_receipt'])==p['root_receipt_sha256']
for key in ['SM_closure_files_sha256','root_files_sha256','inherited_review_binding']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
root=load(p['root_receipt']);assert root['exit_code']==0 and root['kernel_session']==10465
logfile='work/checks/far-only-locality-review-types.log';s=(base/logfile).read_text()
assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==3 and len(examples)==8
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
typefile='work/checks/far-only-locality-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'additional_examples':examples,'consumer_count':8,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256']);body='work/checks/FarOnlyLocality.body.lean';reviewed[body]=sha(body)
closurefile='work/checks/far-only-locality-review-closure.json'
write(closurefile,{'source':p['source'],'source_sha256':p['source_sha256'],'source_id':'thm:single-triple','SM_import_roots':['SM.Farout'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':32,'reviewed_files_sha256':reviewed,'root_receipt':p['root_receipt'],'root_receipt_sha256':sha(p['root_receipt']),'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),'scope':p['scope']})
prior=load('work/reviews/lem-farout.json')
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),'independent_kernel_command':'lake env lean ../checks/far-only-locality-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':True,'checked_declarations':names,'declaration_count':3,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':8,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),'root_successful_result':root,'root_receipt':p['root_receipt'],'root_receipt_sha256':sha(p['root_receipt']),'scope_note':'One exact frozen external body is compiled over the real 32-module SM.Farout dependency closure. Consumers use actual intervals, triples, raw composition children and arrays; no wall geometry assumptions are synthesized.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'far-only-locality-prototype','source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910','verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':names,'prototype_files_sha256':{'FarOnlyLocality':sha('work/checks/FarOnlyLocality.prototype.lean')},'reviewed_files_sha256':reviewed,'import_closure_roots':['SM.Farout'],'import_closure_file_count':32,'embedded_body_count':1,'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':prior['pins'],
 'reason':f'Faithful external algebraic locality step in the proof of thm:single-triple, source281-283. Equality on every actual bounded triple in J gives equality of complete restricted arrays. Exact restriction of the constructed far-only inverse then gives equality of its J coordinate, with the one-leaf convention handled directly. If only one actual increasing triple can differ, every interval not containing its full span satisfies this local equality hypothesis. Independent first kernel {session} checks all three declarations and eight consumers with eleven standard-or-empty axiom traces. This proves the locality conclusion under explicit array hypotheses; wall-germ sign stability, unique changing far-coordinate occurrence, gap geometry, jump and propagation formulas are not established by this helper, so no original theorem is accepted.',
 'mathematical_justification':[
 {'clause':'Full local triple domain and actual ordered positions','assessment':'IncreasingBoundaryTriple consists of any three Fin n positions lower<middle<upper. The hypothesis compares H1 and H2 for every such triple with J.left<=lower and upper<=J.right; the middle is automatically between the endpoints. liftTriple translates each of the three positions by J.left. globalPosition_bounds proves these actual translated endpoints lie in J, so the hypothesis applies to every local triple. Function extensionality then gives equality of the entire restricted arrays. No entries outside J are constrained, and no geometry, determinant or sign-valued restriction is imposed on the arbitrary ring arrays.'},
 {'clause':'Inverse-coordinate locality on nonleaf intervals','assessment':'farOnlyCoordinates is the actual constructed inverse nearFarInverse(0,H)(E), not a free solution variable. Equality of the restricted H arrays therefore gives equality of their constructed local c arrays by congruence. The proved farOnlyCoordinates_restrict identifies each with the restriction of the corresponding global c. For J.leaves>=2, the full local interval has at least three vertices and lifts exactly to J. Evaluating the array equalities at this full interval and composing both restriction equations yields c1(J)=c2(J). This is a source-faithful derivation from the established exact restriction theorem instead of repeating source interval-length induction; it assumes neither the locality conclusion nor an additional inverse-uniqueness premise.'},
 {'clause':'One-leaf convention and all subintervals','assessment':'Every BoundaryInterval has positive leaf count. The proof separately handles J.leaves=1 using the proved identity c(H)(J)=1 for every H, so it never invokes a two-vertex polygon coefficient or a nonexistent geometric G1 condition. If leaves is not one, positivity yields leaves>=2. An independent leaf consumer verifies equality with no array-agreement hypothesis. Two further consumers show equality of the entire restricted c array and of its value on every actual translated local subinterval; this checks that the coordinate locality is compatible with all source subintervals, not only one abstract target.'},
 {'clause':'Exactly the source critical-span exclusion','assessment':'The critical triple is an actual IncreasingBoundaryTriple with pairwise distinct ordered positions x<y<z. The hypothesis allows only that one array entry to differ; it does not require a sign flip or assume geometry. If J does not contain both x and z, any triple whose endpoints lie inside J cannot equal critical: otherwise its bounds would contradict the stated exclusion. Applying the local theorem therefore gives unchanged c. The inclusive inequalities are exact containment of I*=[x,z]; a proper subinterval or a gap may meet its endpoints and is still excluded unless it contains the full span. There is no requirement that J be disjoint from the critical points.'},
 {'clause':'Actual gap and proper-child consumers','assessment':'The left gap is the actual interval [critical.lower,critical.middle]. Containing the full critical span would require critical.upper<=critical.middle, contradicting strict ordering. The right gap similarly would require critical.middle<=critical.lower. Independent consumers verify unchanged c on both, including singleton gaps. For every raw nonunary composition of the exact critical span, the existing strict child-leaf-count theorem gives each child fewer leaves than the span. If a child contained the span, the endpoint inequalities would force its leaf count to be at least that of the span, a contradiction. Thus every actual proper child has unchanged c, as needed in the next source paragraph285; no subset of compositions or child indices is assumed.'},
 {'clause':'Arbitrary changed scalar and output restriction checks','assessment':'A consumer replaces exactly the critical H entry by an arbitrary ring value using Function.update and verifies the off-span conclusion. This tests the intended scalar freedom and does not limit the helper to geometric +/-1 values. Another consumer uses the established farOnlyOutput restriction identity to obtain equality of the full restricted B arrays from the same local H equality, consistent with the gap-value context. These consumer consequences do not assert a changed-coordinate jump or independence on intervals containing the full span.'},
 {'clause':'Scope is a partial algebraic source proof step','assessment':'The theorem starts at source229, its proof at270, and the locality paragraph is281-283. The first sentence of that paragraph additionally says that the critical triple appears as far data in exactly one coordinate formula. These three helper declarations do not themselves formalize that occurrence statement, nor do they derive equality of all noncritical geometric arrays from a continuous wall germ after a common shrink. They do not prove gap G1, epsilon signs, contracted polygons, composition splitting, coefficient jumps or propagation through larger intervals. Their conditional algebraic locality conclusion is faithful and useful, but the full thm:single-triple remains unaccepted.'}],
 'independence':'The reviewer independently read the current authoritative source and all three exact new proofs, inspected their transparent canonical definitions, and authored only new review consumers and reports. No implementation, source, declaration map, root receipt or frozen prior review was changed. This new locality body contains no reviewer-authored implementation fragment. The canonical Farout dependency retains its separately disclosed two marking-fragment contributions and fresh noncontributing review, bound through the inherited reports.',
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Wall-germ noncritical sign stabilization and actual geometric-array comparison.','Unique occurrence of the changing triple in a far-coordinate formula.','Gap geometry and epsilon identities.','Composition splitting and critical-coordinate jump.','Contraction, propagation and both final wall-response formulas.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash.','No complete corner wall law, soft theorem, R theorem or overall stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/far-only-locality-prototype.json';write(out,d);print(out,sha(out));print('PASS:3 declarations+8 consumers,11 standard-or-empty traces; conditional algebraic locality only; no original acceptance.')
