from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/gap-split-products-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256'] and sha(p['trace'])==p['trace_sha256'] and sha(p['examples'])==p['examples_sha256']
for key in ['SM_closure_files_sha256','root_files_sha256','root_receipts_sha256','inherited_review_binding']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
roots={f:load(f) for f in p['root_receipts_sha256']};assert all(r['exit_code']==0 for r in roots.values())
logfile='work/checks/gap-split-products-review-types.log';s=(base/logfile).read_text();assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==26 and len(examples)==10
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
oldtypes=load('work/checks/critical-cut-reviewed-types.json')['types'];oldnames=p['checked_declarations_by_body']['CriticalCutSplit']
assert len(oldnames)==14 and all(types[n]==oldtypes[n] for n in oldnames)
typefile='work/checks/gap-split-products-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'additional_examples':examples,'consumer_count':10,'all_14_predecessor_types_unchanged':True,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/gap-split-products-review-closure.json'
write(closurefile,{'source':p['source'],'source_sha256':p['source_sha256'],'source_id':'thm:single-triple','SM_import_roots':['SM.Farout'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':32,'reviewed_files_sha256':reviewed,'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),'scope':p['scope']})
prior=load('work/reviews/lem-farout.json')
failed=dict(p['prior_failed_independent_run']);failed['source_sha256']=sha(failed['source']);failed['log_sha256']=sha(failed['log'])
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),'independent_kernel_command':'lake env lean ../checks/gap-split-products-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':False,'prior_failed_independent_run':failed,'checked_declarations':names,'declaration_count':26,'new_declaration_count':12,'all_14_predecessor_types_unchanged':True,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':10,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),'root_successful_results':roots,'root_receipts_sha256':p['root_receipts_sha256'],'scope_note':'The exact frozen CriticalCutSplit and GapSplitProducts bodies compile over the actual 32-module canonical Farout closure. All fourteen predecessor types match the earlier trace. Ten consumers test actual raw children, unary gaps, zero scalar behavior and erased full sums.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'gap-split-products-prototype','source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910','verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':p['checked_declarations_by_body']['GapSplitProducts'],'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},'reviewed_files_sha256':reviewed,'import_closure_roots':['SM.Farout'],'import_closure_file_count':32,'embedded_body_count':2,'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':prior['pins'],
 'reason':f'Faithful exact child/cut product and full weighted-sum factorization development in the partial proof of thm:single-triple. The actual binary outer gap composition and full refined-child bijection partition every raw child coordinate between the two actual split compositions. Interior positions are exactly the distinguished middle plus two disjoint gap interior sets. Both ordinary and erased products are transported through these actual sets, with no division, cancellation or nonzero hypothesis. Complete sums over all middle-cut compositions then factor into both full gap sums by the proved index equivalence and distributivity. Independent second kernel {session} passes 26 declarations and ten consumers with 36 standard-or-empty traces; fourteen predecessor types are unchanged. The preserved first reviewer failure concerned only a dependent-product rewrite in a consumer proof, with no statement or implementation change. Geometric epsilon transport and complete wall jumps/propagation remain outside this scope, so no original source theorem is accepted.',
 'mathematical_justification':[
 {'clause':'Exact interior-index and physical-position products','assessment':'prod_interiorPositions identifies the image of every actual interior index with the complete physical interior cut set, using the proved exact interior-position membership equivalence. The existing indexMarks product transport then replaces the full index product by the physical-position product. For a deleted index k, injectivity of interiorPosition proves that the image of univ.erase k is exactly the physical interior set with interiorPosition(k) erased. Conversely every surviving physical position has an interior index which cannot be k. Reusing the arbitrary marked-product theorem gives the erased product identity. Both proofs require only CommMonoid; no scalar is divided out, assumed nonzero, or cancelled.'},
 {'clause':'Actual two-gap outer composition and raw refinement','assessment':'gapBaseComposition is the raw two-part composition with the three actual cuts [t.lower,t.middle,t.upper]. Its strict ordering follows from the two strict inequalities of the critical triple. gapRefinement embeds every raw middle-cut composition as a refinement of that exact outer cut list: the lower and upper cuts are already its endpoints and the middle is its defining retained cut. No arbitrary surrogate outer composition or narrowed inner family is used.'},
 {'clause':'Every actual raw child factor appears once','assessment':'gapComposition_child_product instantiates the already proved full refined-child product bijection with gapBaseComposition and the actual middle-cut composition. The two recovered inner compositions are definitionally the two filtered gap compositions from gapCompositionEquiv. Expanding the two-element outer product therefore yields exactly the two gap child products. The reconstructed fine cut-set composition is then identified with the original raw composition by cutSet_toComposition. This retains the full raw part count and every actual interval factor. Independent consumers separately recover every actual left and right child as an actual original child interval, and an arbitrary raw-pair consumer verifies the complete joined product for every pair of gap compositions.'},
 {'clause':'Complete interior partition with the middle exactly once','assessment':'The whole composition interior set is proved equal to the insertion of t.middle into the union of the two split interior sets. For a whole interior point, trichotomy places it strictly left of the middle, at the middle, or strictly right; the literal split-cut filter lemmas establish its corresponding gap membership. Conversely each gap interior point is a whole interior point, and the retained middle is strictly between whole endpoints. A point in both gap interiors would be simultaneously less and greater than the middle, so those interiors are disjoint. The middle is excluded from both by strict gap-interior inequalities. These facts justify prod_insert and prod_union without omission or duplicated factors.'},
 {'clause':'Full and erased cut-factor products','assessment':'The full index product is first moved to the exact physical interior set. The interior partition then gives one distinguished middle factor times both complete gap interior products. For the erased version, the proved index-erasure correspondence first removes the actual chosen middle position; erase_insert removes precisely that inserted point and leaves the two disjoint gap interiors. Both gap products are then returned to their full interior-index products. The erased result is proved directly, never by dividing the full identity by f(middle). It therefore remains valid even when the critical factor or any retained factor is zero.'},
 {'clause':'Complete weighted composition sums','assessment':'middle_weighted_composition_sum reindexes the entire original MiddleComposition sum through the exact raw gapCompositionEquiv. Each summand is rewritten using both the full cut-product and full child-product identities. The inverse-forward equivalence equation recovers the original arbitrary pair of gap compositions. Finite distributivity in a commutative semiring factors the double sum as the middle scalar times the product of both complete gap weighted sums. The erased version starts with the physical middle-erased set, decomposes it directly into the same two gap interiors and applies the full child-product identity, then performs the same finite distributivity. Neither theorem assumes a response law or an already factored weighted summand.'},
 {'clause':'Unary-gap, zero-factor and omitted-value consumers','assessment':'Independent raw-pair consumers specialize each gap separately to its unary composition. The unary child product becomes the actual X(leftGap) or X(rightGap), so the source interval coordinate is retained while the corresponding cut product is empty. Another consumer proves that when both gap compositions are unary, deleting the unique middle gate leaves product one for arbitrary scalar functions. The zero-middle full-sum consumer obtains zero from the full weighted identity, while a separate zero-middle erased-sum consumer still obtains the two gap sums, showing that no zero factor is cancelled. Further consumers prove that each erased product and the full erased sum are unchanged under any alteration of the omitted middle scalar.'},
 {'clause':'Algebraic generality and distinction from epsilon geometry','assessment':'Product transports assume only a commutative monoid and sum factorizations only a commutative semiring. They therefore specialize to the source rings with invertible two and also remain valid with zero divisors or zero gates; there is no hidden field or nontriviality premise. The scalar function f reads actual physical cut positions. When later specialized to a full-span far gate, the gap sums still use those same physical scalar values. Identifying them with the natural gap far gates and choosing E or B according to the wall epsilon requires the separate geometric sign-ratio identities. Those epsilon identities are not assumed or proved by this algebraic batch.'},
 {'clause':'Source scope remains partial','assessment':'The body covers the exact product and weighted-sum content behind source285-289 and304-317. The original wall theorem additionally needs a common punctured-neighborhood sign comparison, gap G1, epsilon geometry, actual critical-coordinate inverse and reversed-output differences, contracted polygons and larger-interval propagation. The already reviewed critical scalar-difference body and this product body have not yet been assembled here into those full conclusions. Thus the implementation is faithful within its explicit algebraic helper scope; thm:single-triple and the final corner wall laws remain unaccepted.'}],
 'independence':'The reviewer independently read the source, exact new body, actual frozen splitting body and canonical refined-child/interior-index definitions, and wrote only new consumer and review files. No mathematical implementation, authoritative source, map, root receipt or frozen report was changed. The first reviewer run was preserved and only the failed dependent-product consumer proof was corrected. This new body contains no reviewer-authored implementation fragment. The dependency on canonical Farout retains its separately disclosed marking-fragment provenance and independent fresh review through the bound prior reports.',
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Wall sign stabilization, nondegenerate gap geometry and epsilon identities.','Assembly of actual critical-coordinate c and reversed-output differences.','Contracted polygon/root identification and larger-interval propagation.','Both final single-triple wall-response formulas.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash.','No complete corner wall law, soft theorem, R theorem or overall stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/gap-split-products-prototype.json';write(out,d);print(out,sha(out));print('PASS:26 declarations+10 consumers;36 standard-or-empty traces;14 predecessor types unchanged; exact gap products/sums only; no original acceptance.')
