from pathlib import Path
from hashlib import sha256
import json,re,datetime
base=Path(__file__).resolve().parents[2]
def sha(rel):return sha256((base/rel).read_bytes()).hexdigest()
def load(rel):return json.loads((base/rel).read_text())
proto=load('work/reviews/relative-general-position-prototype.json')
c=load('work/checks/relative-general-position-canonical-review-closure.json')
result=load('work/checks/relgp-port-audit-result.json')
receipt=load('work/checks/checkpoint-058-output.json')
audit=load('work/checks/checkpoint-058-declaration-audit.json')
log=(base/'work/checks/relative-general-position-canonical-review-types.log').read_text()
assert not re.search(r'error[:(]',log)
assert result['exit_code']==0 and result['successful_audit_session']==93283
assert receipt['passed'] and not receipt['stage_accepted']
assert result['audit_receipt_sha256']==sha('work/'+result['audit_receipt'])
assert result['build_and_audit_log_sha256']==sha('work/'+result['build_and_audit_log'])
assert result['declaration_audit_sha256']==sha('work/'+result['declaration_audit'])
assert sha('reference/SM/sm-1-polygons.tex')==proto['source_sha256']
assert all(sha(k)==v for k,v in c['canonical_SM_files_sha256'].items())
assert all(sha('work/lean/'+k)==v for k,v in receipt['project_sha256'].items())
assert all(sha(k)==v for k,v in receipt['bundle_sha256'].items())
target=next(x for x in audit['audit']['declarations'] if x['declaration']=='SM.relative_general_position')
assert target['kind']=='theorem' and target['module']=='SM.RelativeGeneralPosition'
sh=sha256(json.dumps(target['semantic_dependencies'],sort_keys=True,separators=(',',':')).encode()).hexdigest()
assert sh==audit['statement_hashes']['thm:relgp']==result['statement_sha256']
assert sh=='ea9976b281dfda84381a7c7e0fbf0a258dd7e7b5a8d8d03cb86db9639e8100ec'
semnames={d['declaration'] for d in target['semantic_dependencies']}
required=['SM.RelativeGeneralPositionPath','SM.RelativeGeneralPositionPath.mk','SM.RegularWallKind','SM.WallGerm.HasRegularWallKind','SM.WallGerm','SM.WallGerm.mk','SM.WallGerm.Simple','SM.WallGerm.SignChanges','SM.WallGerm.FlatAt','SM.WallGerm.BigonAt','SM.WallGerm.SlidingAt','SM.WallGerm.TripleAt','SM.WallGerm.ExtensionAt','SM.WallGerm.PureCutAt','SM.WallGerm.CuspAt','SM.Generic','SM.G1','SM.G2','SM.Regular','SM.RegularPair','SM.LabelledTuple','SM.scalarCoordinates','SM.tupleCoordinates','SM.uniformMeshCell','SM.uniformMeshPoint']
assert set(required)<=semnames
examples=proto['evidence']['additional_examples'];names=c['checked_declarations'];axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",log)
 if m: axioms[n]=[s.strip() for s in m[1].split(',') if s.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in log,n
  axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'}
for n in names:
 start=log.index(n+' ');end=log.index("'"+n+"'",start);types[n]=log[start:end].strip()
for name in ['point-control-geometry-prototype','point-control-walls-prototype','concurrence-order-prototype','relative-general-position-prototype']:
 d=load('work/reviews/'+name+'.json');old=(base/d['evidence']['independent_trace_log']).read_text()
 for n in d['evidence']['checked_declarations']:
  start=old.index(n+' ');end=old.index("'"+n+"'",start);assert types[n]==old[start:end].strip(),n
sem={'declaration':'SM.relative_general_position','statement_sha256':sh,'semantic_dependency_count':len(semnames),'semantic_declarations':sorted(semnames),'required_transparent_input_output_definitions_present':required,'semantic_dependency_record_sha256':{d['declaration']:sha256(json.dumps(d,sort_keys=True,separators=(',',':')).encode()).hexdigest() for d in target['semantic_dependencies']},'canonical_printed_types':types,'canonical_printed_type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'all_36_prototype_canonical_printed_types_equal':True}
(base/'work/checks/thm-relgp-canonical-semantic-review.json').write_text(json.dumps(sem,indent=2)+'\n')
evidence={'independent_trace_source':'work/checks/relative-general-position-canonical-review-types.lean','independent_trace_source_sha256':sha('work/checks/relative-general-position-canonical-review-types.lean'),'independent_trace_log':'work/checks/relative-general-position-canonical-review-types.log','independent_trace_log_sha256':sha('work/checks/relative-general-position-canonical-review-types.log'),'independent_kernel_command':'lake env lean ../checks/relative-general-position-canonical-review-types.lean','independent_kernel_session':92115,'independent_kernel_exit_code':0,'first_independent_run_passed':True,'checked_declarations':names,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':len(examples),'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},'same_seven_examples_as_full_prototype':True,'all_36_prototype_canonical_printed_types_equal':True,'independent_closure_evidence':'work/checks/relative-general-position-canonical-review-closure.json','independent_closure_evidence_sha256':sha('work/checks/relative-general-position-canonical-review-closure.json'),'canonical_semantic_evidence':'work/checks/thm-relgp-canonical-semantic-review.json','canonical_semantic_evidence_sha256':sha('work/checks/thm-relgp-canonical-semantic-review.json'),'root_result_file':'work/checks/relgp-port-audit-result.json','root_result_sha256':sha('work/checks/relgp-port-audit-result.json'),'successful_build_session':93283,'successful_build_exit_code':0,'successful_build_log':'work/checks/checkpoint-058-lean-check.log','successful_build_log_sha256':sha('work/checks/checkpoint-058-lean-check.log'),'audit_receipt':'work/checks/checkpoint-058-output.json','audit_receipt_sha256':sha('work/checks/checkpoint-058-output.json'),'declaration_audit':'work/checks/checkpoint-058-declaration-audit.json','declaration_audit_sha256':sha('work/checks/checkpoint-058-declaration-audit.json'),'transparent_predicates_printed':['SM.RelativeGeneralPositionPath','SM.WallGerm.HasRegularWallKind','SM.CurveCubeSubdivision.TimedEventCertificate'],'non_failing_trace_warnings':'Reviewer letI proof style warnings only. No kernel errors or unregistered axioms.'}
port={'review_schema':'independent-full-source-port-review-v1','id':'relative-general-position-port','source_id':'thm:relgp','reviewer':proto['reviewer'],'implementer':proto['implementer'],'verdict':'faithful','source_claim_accepted':False,'statement_sha256':sh,'source':proto['source'],'source_sha256':proto['source_sha256'],'parameters_reviewed':True,'definition_equivalence_reviewed':True,'in_theorem_library':True,'reason':'All five canonical namespace bodies match their already independently reviewed prototype/body sources byte-for-byte. Only import headers replace embedded predecessors; no definition or proof changed. All280 prior SM modules are unchanged, Supplemental gained exactly import SM.RelativeGeneralPosition, and the actual recursive SM closure is exactly the prior124 plus the five new modules. The canonical-only import trace independently checks36 declarations and reruns the same seven substantive raw-source/consumer checks. Every one of the36 canonical printed types exactly matches its prior prototype trace. The trace passed with standard axioms only. The full canonical semantic dependency closure includes the actual input/output structures and all named wall predicates, and its hash is independently recomputed from the successful current audit058. This report certifies the exact port; the separate thm-relgp report supplies the full original source fidelity verdict.','ports':c['ports'],'main_declarations':names,'reviewed_files_sha256':c['SM_closure_files_sha256'],'import_closure_roots':['SM.RelativeGeneralPosition'],'import_closure_file_count':c['SM_closure_count'],'prior280_unchanged':True,'current_SM_count':285,'prototype_review':'work/reviews/relative-general-position-prototype.json','prototype_review_sha256':sha('work/reviews/relative-general-position-prototype.json'),'evidence':evidence,'not_certified':['No overall stage completion or state-sum wall/soft theorem acceptance.','This exact-port report does not itself edit the original declaration map.']}
(base/'work/reviews/relative-general-position-port.json').write_text(json.dumps(port,indent=2)+'\n')
review={k:proto[k] for k in ['reviewer','implementer','source','source_lines','source_sha256','parameters_reviewed','definition_equivalence_reviewed','independence','pins','mathematical_justification']}
review.update({'review_schema':'independent-full-source-review-v1','id':'thm:relgp','source_id':'thm:relgp','source_line':1385,'labels':['thm:relgp'],'declaration':'SM.relative_general_position','module':'SM.RelativeGeneralPosition','verdict':'faithful','source_claim_accepted':True,'statement_sha256':sh,'in_theorem_library':True,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'reason':proto['reason'].split(' This is a full-source prototype fidelity verdict.')[0]+' The reviewed bodies are now exact canonical modules. Independent canonical-only kernel92115 passes36 implementation declaration checks and the same seven substantive consumer theorems; all36 printed types exactly match the separately reviewed prototypes. The successful whole-project audit058 and independently recomputed semantic dependency hash bind the theorem, transparent input/output structures, and all named wall definitions. The original thm:relgp is therefore faithful and eligible for map acceptance with this exact review.','reviewed_files_sha256':c['SM_closure_files_sha256'],'import_closure_roots':['SM.RelativeGeneralPosition'],'import_closure_file_count':129,'semantic_dependency_count':len(semnames),'required_semantic_definitions_checked':required,'prototype_review':'work/reviews/relative-general-position-prototype.json','prototype_review_sha256':sha('work/reviews/relative-general-position-prototype.json'),'port_review':'work/reviews/relative-general-position-port.json','port_review_sha256':sha('work/reviews/relative-general-position-port.json'),'inherited_review_binding':proto['inherited_review_binding'],'evidence':evidence,'audit_context':{'receipt':'work/checks/checkpoint-058-output.json','receipt_sha256':sha('work/checks/checkpoint-058-output.json'),'root_audit_session':93283,'root_audit_exit_code':0,'passed':True,'stage_accepted':False,'audited_local_declarations':3455,'mapped_claims':31,'audited_SM_modules':285,'audited_project_files':291,'frozen_bundle_files':38,'all_receipt_project_and_bundle_hashes_checked_at_review':True,'scope':'Development audit058 covers the canonical theorem and current library before this review is added to its declaration-map row. This review does not pretend a subsequent accepted-map audit has already passed.'},'acceptance_scope':{'original_claim':'thm:relgp','proofs_added_if_mapped_accepted':1,'current_map_was_not_edited_by_reviewer':True,'other_original_claims_accepted':0,'main_wall_or_soft_targets_accepted':0,'stage_complete':False},'not_certified':['No overall focused handoff completion or main state-sum wall laws, soft theorem or unconditional R theorem is accepted by this one claim.','The full theorem is an existential mathematical construction; no executable numerical waypoint algorithm or runtime bound is claimed.','Smooth hypersurface/transversality geometry is proved through explicit open smooth graph, inverse and the same actual path nonzero derivative certificate; no separate manifold API predicate is claimed.']})
(base/'work/reviews/thm-relgp.json').write_text(json.dumps(review,indent=2)+'\n')
print('Canonical review faithful, semantic hash',sh)
print('reviews/thm-relgp.json SHA',sha('work/reviews/thm-relgp.json'))
print('reviews/relative-general-position-port.json SHA',sha('work/reviews/relative-general-position-port.json'))
print('Declarations',len(names),'consumer checks',len(examples),'semantic definitions',len(semnames),'import closure',len(c['SM_closure_files_sha256']))
