from pathlib import Path
from hashlib import sha256
import re,json,sys,datetime
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pf='work/checks/geometric-gap-response-review-preparation.json';p=load(pf)
for k in ['sources_sha256','SM_closure_files_sha256','all_327_canonical_SM_files_sha256','root_receipts_sha256','root_files_sha256','prior_checkpoint_bindings_sha256','example_files_sha256']:
 for f,h in p[k].items():assert sha(f)==h,(k,f)
assert sha(p['trace'])==p['trace_sha256']
log='work/checks/geometric-gap-response-review-types.log';s=(base/log).read_text()
assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==42 and len(examples)==31
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n]) <= {'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
oldtypes=load('work/checks/boundary-gate-stability-reviewed-types.json')['types']
assert len(oldtypes)==27 and all(types[n]==t for n,t in oldtypes.items())
tf='work/checks/geometric-gap-response-reviewed-types.json'
write(tf,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,
 'checked_declarations':names,'additional_examples':examples,'trace_log':log,'trace_log_sha256':sha(log),
 'independent_kernel_session':session,'exit_code':0,'all_27_predecessor_types_unchanged':True})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
cf='work/checks/geometric-gap-response-review-closure.json'
write(cf,{'source_id':p['source_id'],'sources_sha256':p['sources_sha256'],'SM_import_roots':p['SM_import_roots'],
 'SM_closure_count':p['SM_closure_count'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],
 'all_327_canonical_SM_files_sha256':p['all_327_canonical_SM_files_sha256'],'reviewed_files_sha256':reviewed,
 'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],
 'prior_checkpoint_bindings_sha256':p['prior_checkpoint_bindings_sha256'],'preparation':pf,'preparation_sha256':sha(pf),
 'trace':p['trace'],'trace_sha256':sha(p['trace']),'scope':p['scope']})
prior=load('work/reviews/boundary-gate-stability-prototype.json')
for f,h in prior['pins']['pin_files_sha256'].items():assert sha(f)==h
failures=p.get('prior_failed_independent_runs',[])
for f in failures:
 for k in ['source','log','examples','preparation']:f[k+'_sha256']=sha(f[k])
newnames=[n for b in p['new_body_order'] for n in p['checked_declarations_by_body'][b]]
assert len(newnames)==15
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),
 'independent_trace_log':log,'independent_trace_log_sha256':sha(log),
 'independent_kernel_command':'lake env lean ../checks/geometric-gap-response-review-types.lean',
 'independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':not failures,
 'prior_failed_independent_runs':failures,'checked_declarations':names,'declaration_count':42,'new_declaration_count':15,
 'all_27_predecessor_types_unchanged':True,'declaration_axioms':{n:axioms[n] for n in names},
 'additional_examples':examples,'additional_example_count':31,'new_consumer_count':12,'additional_examples_passed':True,
 'additional_example_axioms':{n:axioms[n] for n in examples},'transparent_definitions_printed':p['transparent_definitions_printed'],
 'supporting_types_printed':p['supporting_types_printed'],'reviewed_types':tf,'reviewed_types_sha256':sha(tf),
 'independent_closure_evidence':cf,'independent_closure_evidence_sha256':sha(cf),
 'root_successful_results':{f:load(f) for f in p['root_receipts_sha256']},'root_receipts_sha256':p['root_receipts_sha256']}
domain='work/reviews/single-triple-n3-domain-note.json'
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'geometric-gap-response-prototype',
 'source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':sha(p['source']),
 'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],
 'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910',
 'verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,
 'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),
 'main_declarations':newnames,'main_declarations_by_body':{b:p['checked_declarations_by_body'][b] for b in p['new_body_order']},
 'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},
 'reviewed_files_sha256':reviewed,'import_closure_roots':p['SM_import_roots'],'import_closure_file_count':p['SM_closure_count'],
 'embedded_body_count':11,'evidence':evidence,'pins':prior['pins'],'prior_checkpoint_bindings_sha256':p['prior_checkpoint_bindings_sha256'],
 'reason':'Faithful partial geometric response and actual full-span wall-germ identity. A common positive radius is obtained by continuity on the real interval subtype. Actual noncritical samples transfer the wall determinant identities to every gap composition gate. The complete ordinary/reversed gap sums become the source U/V values, yielding the actual critical c/B response. At full span, the rooted tree coefficient on each punctured side is the actual far-only output and all gap factors transport to their center values. The restricted word has the actual cyclic label map and G1 off the critical span, allowing nonleaf gap B to be identified with its physical closing-root coefficient. All42 types and31 consumers pass with standard axioms only, and all27 prior types match. The proper contraction/propagation branch and a separate +/-1 conclusion for the sign-change prefactor remain outside this review.',
 'mathematical_justification':[
 {'clause':'Actual common radius on the continuous wall germ','assessment':'boundary_values_stable_near_center uses the actual WallGerm curve on the open real interval subtype, not an arbitrary global extension or a differentiable replacement. Its continuousAt statement is explicitly at zeroParameter. Pulling back the three previously proved ambient-neighborhood events through that continuous map gives one event in the parameter neighborhood for all noncritical arrays and all excluded inverse/output intervals. The already canonical eventually_center_iff_radius equivalence extracts a positive radius bounded by the original germ radius using the metric ball at zero and the minimum of radii. The result quantifies every actual parameter with absolute value below that common radius, including zero. The independent consumer specializes the same radius simultaneously to both actual sideTime/sideTuple maps; it does not choose a separate radius for a side, triple, or interval.'},
 {'clause':'Source U/V and their exact allowed sign domain','assessment':'wallGapU chooses the actual unit array E when epsilon=1 and the complete farOnlyOutput B otherwise; wallGapV interchanges those two. The source epsilon is +/-1, and every signed-sum theorem explicitly assumes that disjunction, with geometric callers deriving it from the three distinct real coordinates. The arbitrary zero branch of the total Lean definitions is not certified as an additional source case. Independent consumers verify the exact four +/-1 cases, reversal of epsilon, the one-leaf values U=V=1, and the nonleaf E choices U(+1)=V(-1)=0. Thus the source formal open-word convention does not introduce a two-vertex polygon coefficient.'},
 {'clause':'Complete signed and reversed gap sums','assessment':'cutWeightedSum_signed_inverse compares every actual scalar factor in every unchanged raw interval composition with -(epsilon*H(farTriple))/2. For epsilon=1 the complete sum is the actual F_H(c), which equals E by the already proved inverse equation. For epsilon=-1 it is the actual F_(-H)(c)=B, with c still the inverse for H. The reversed-sum theorem negates the entire gate function, so epsilon=1 yields B and epsilon=-1 yields E. It never replaces c(H) by c(-H), drops unary compositions, or cancels a possibly zero gate. The complete finite product/sum bridge and prior empty/zero-factor checks remain bound through the canonical algebra report.'},
 {'clause':'Every gap factor uses the physical wall endpoints','assessment':'For each left-gap interior cut, the proof obtains its physical position strictly between lower and middle, hence also between lower and upper. The global sampled triple cannot be the critical triple because its middle is strictly below the critical middle. The local left-gap far triple cannot be critical because its upper endpoint is the critical middle rather than upper. Therefore the assumption that H agrees with the actual wall array only off the critical triple applies to both samples. The frozen geometric sign bridge gives exactly the left epsilon factor. The right proof uses a middle strictly above the critical middle and a local lower endpoint equal to that middle; both samples are again noncritical, and the printed right epsilon orientation is retained. Unfolding fixedFarGate uses only the proved strict-interior branch. Nearby points need not be collinear and the critical gate need not be zero.'},
 {'clause':'Four geometric gap sums and actual critical inverse/output responses','assessment':'geometric_gap_sums applies the two complete signed-sum identities to both physical gaps, using epsilon nonzero from the explicit source coordinate inequalities. Reversal is handled by the proved pointwise fixedFarGate(-H)=-fixedFarGate(H), preserving the actual inverse array c(H). The four conclusions are the two ordinary U values and the two reversed V values. In geometric_critical_inverse_response and geometric_critical_output_response, both arrays agree with the same actual wall geometry off the critical triple, so they agree with each other there. The already proved actual algebraic critical responses apply; substituting the four exact gap identities yields the U product for c and the sum of U and V products for B. No response equation is a premise. An independent consumer sets the critical H entry to any ring value using Function.update and still obtains the wall-centered ordinary gap sum, explicitly checking that the argument does not evaluate the critical gate at zero.'},
 {'clause':'Gap values transport to the wall center','assessment':'The actual geometric stability theorem equates the full B output between a close tuple and the center on every interval excluding the complete critical span. Both gaps exclude that span by their strict endpoint inequalities. Since E is the same unit array on either tuple, the conditional U/V definitions consequently preserve both gap values. The independent consumer proves this transport for arbitrary arrays and any excluded interval and sign, then applies it to the arbitrary-critical-entry geometric gap sum. No continuity of a nongeneric polygon amplitude or individual tree summand is assumed.'},
 {'clause':'Actual rooted full-span response on both sufficiently close sides','assessment':'full_span_tree_response chooses the common radius above and permits arbitrary negative sMinus and positive sPlus inside it, not merely a symmetric pair. Their actual generic-punctured proofs provide G1 and hence the already accepted identification of the rooted tree coefficient with the full-interval far-only output. The span equality identifies this with the critical B response. The baseline-side B values on both gaps are equal to their center values, and E is unchanged, so all four U/V factors in the final expression are evaluated at the wall center. The physical root g is retained throughout. The independent consumer specializes the theorem to the actual positive and negative sideTuple maps at the same positive distance, checking sign orientation, subtype bounds, and actual tree coefficients. This proves the literal half-difference-prefactor full-span identity; it does not separately prove that this prefactor is +/-1 under the source sign-change condition.'},
 {'clause':'Exact restricted-word cyclic labels','assessment':'restrictedVertexIndex g J j is the existing boundaryIndex at J.globalPosition((j-1).val). Thus residue zero labels the actual last vertex of the contiguous closed word, exactly as in the accepted Farout construction, while residue one labels the first. Injectivity follows in three steps: injectivity of boundaryIndex, strictness and therefore injectivity of globalPosition, and injectivity of the residue value map followed by adding one to both sides. No cropped or repeated label set is substituted. Independent consumers check the actual tuple evaluation P(restrictedVertexIndex j) and equality of these original labels if and only if equality of the local labels.'},
 {'clause':'Actual closed-word G1 without genericity at the wall','assessment':'For any distinct local labels i,j,k, the restricted index injection makes their three original labels distinct. If their unordered support were the critical one, membership of the critical lower and upper labels in that support would place both actual positions inside J: boundaryIndex injectivity identifies each with a globalPosition value, and the actual globalPosition bounds give the endpoint inequalities. This contradicts exclusion of the whole critical span. The singleton-zero theorem then gives nonzero chi for those exact original vertices, definitionally the chirotope of the actual restrictedWordTuple. Both gaps exclude the span, so the advertised nonleaf closed gap polygons satisfy G1. The final gap theorem keeps the source leaf-count conditions explicit. The stronger intermediate G1 predicate on a one-leaf word is only a vacuous distinct-label predicate, not a claim that a two-vertex polygon amplitude exists.'},
 {'clause':'Physical closing root and nonleaf coefficient bridge','assessment':'The independent nonleaf consumer combines the newly derived G1 condition with the canonical farOnlyOutput_restricted_tree theorem. It identifies the actual J coordinate of the original wall far-only output with the tree coefficient of the exact closed word rooted at local zero, and derives the required local size at least three from the nonleaf bound. A separate consumer simultaneously checks G1 and the physical closing edge from the actual last boundary vertex to the first. No global G1 P is added to these conclusions; this is precisely the source use of nondegenerate closed gap coefficients evaluated at wall data.'},
 {'clause':'Source-domain and remaining limitations','assessment':'The three wall vertices are supplied by explicit affine-coordinate equalities and distinct real coordinate assumptions in all geometric response declarations. No inference of geometric distinctness from singleton Zpt at n=3 is made, and the separately bound source note remains applicable. These sign identities require even less than the printed nonzero direction, but no nonzero direction or point-injectivity conclusion is inferred from that weaker helper domain. The full-span formula holds without an explicit sign-change premise, with its actual half-difference prefactor; the separate source conclusion that delta is +/-1 still needs the source sign-change argument when assembling the whole original theorem. No proper-span contracted polygon, larger-interval propagation, complete wall law, soft theorem, or R theorem is certified by these15 new helpers.'}],
 'independence':'This reviewer independently read all six new frozen bodies and the full relevant source, inspected the actual canonical topology, tuple/root, transform, and restriction definitions, and wrote only independent consumers and review evidence. No implementation, source, map, root receipt, or prior frozen review was edited. The new common-neighborhood consumer and the root implementation are separate proof artifacts; the root neighborhood implementation was already authored before this consumer preparation. The earlier disclosed inverse-difference conceptual overlap remains resolved and bound through its existing independent review. All27 prior implementation types match their independent successful trace exactly.',
 'separate_source_domain_note':domain,'separate_source_domain_note_sha256':sha(domain),
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['The source sign-change conclusion that the actual half-difference prefactor is +/-1.','Reconstruction or explicit source-equivalent packaging of the affine wall-coordinate data: these helpers take the displayed coordinate equalities and distinct xi as input rather than proving their existence from unordered wall data.','Proper-span contracted polygon, its physical root and genericity, and larger-interval propagation.','Assembly of the entire original thm:single-triple, remaining corner wall laws, soft theorem and R.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash for these external helpers.','No geometric-injectivity inference from singleton Zpt at n=3.','No two-vertex polygon amplitude for a one-leaf gap.','No proper-span contraction/propagation or overall stage completion.']}
out='work/reviews/geometric-gap-response-prototype.json';write(out,d)
print(out,sha(out));print('PASS42 declarations+31 consumers;73 standard-or-empty traces;27 prior types unchanged;62-module closure;327 canonical files unchanged; no original acceptance.')
