from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/refinement-transport-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256']
for key in ['root_receipts_sha256','root_files_sha256','SM_closure_files_sha256','inherited_review_binding']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
assert sha(p['trace'])==p['trace_sha256'] and sha(p['examples'])==p['examples_sha256']
logfile='work/checks/refinement-transport-review-types.log';s=(base/logfile).read_text();assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==41 and len(examples)==14
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 i=m.start();j=s.index("'"+n+"'",i);types[n]=s[i:j].strip()
typefile='work/checks/refinement-transport-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'consumer_count':14,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/refinement-transport-review-closure.json'
write(closurefile,{'status':'independent kernel passed; four exact frozen external bodies reviewed','source':p['source'],'source_sha256':p['source_sha256'],
 'SM_import_roots':p['SM_import_roots'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':14,'reviewed_files_sha256':reviewed,
 'embedded_frozen_bodies':{n:sha('work/checks/'+n+'.body.lean') for n in p['body_order']},'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],
 'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),'examples':p['examples'],'examples_sha256':sha(p['examples']),
 'scope':'Actual consecutive pairs/triples, full raw child-index/product transport, and every marked-index/complement/product/sum transport; no coefficient-factorization or original claim acceptance.'})
roots={}
for n in p['body_order']:
 f='work/checks/'+n+'-prototype-result.json';roots[n]=dict(load(f),receipt=f,receipt_sha256=sha(f))
old=load('work/reviews/def-nearfar.json')
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),
 'independent_kernel_command':'lake env lean ../checks/refinement-transport-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':False,
 'prior_failed_independent_run':{'session':85368,'exit_code':1,
  'source':'work/checks/refinement-transport-review-first.lean','source_sha256':sha('work/checks/refinement-transport-review-first.lean'),
  'log':'work/checks/refinement-transport-review-first.log','log_sha256':sha('work/checks/refinement-transport-review-first.log'),
  'reason':'The unary marking-sum consumer reduced to a unique default Finset(Fin 0); an explicit subsingleton equality identifies it with the empty set. This is a reviewer normalization proof correction only. All implementation traces passed, and no consumer statement or implementation was changed.'},
 'checked_declarations':names,'declaration_count':41,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':14,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},
 'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),
 'root_successful_results':roots,'scope_note':'The independent trace uses the actual canonical raw composition, near-array and marked-refinement definitions, plus the four byte-identical external bodies. It checks the actual selected intervals, sample entries, products, sums and edge cases; root compilation alone does not establish this fidelity.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'refinement-transport-prototype','source_id':'lem:farout','source_line':146,
 'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':'Proof180-199: exact refinement indexing180-187, actual neighboring samples190-193, full child-coordinate product194, and all independent marked selections195-197. The complete factorization151 is not yet certified.',
 'additional_source_sha256':old['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910',
 'verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,
 'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':names,'main_declarations_by_body':p['checked_declarations_by_body'],
 'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},'reviewed_files_sha256':reviewed,'import_closure_roots':p['SM_import_roots'],'import_closure_file_count':14,'embedded_body_count':4,
 'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':old['pins'],
 'reason':f'Faithful external supporting development for the source refinement proof. Actual raw parts are exactly consecutive cut pairs; actual neighboring near triples are uniquely fixed by their physical middle cut. All recovered inner child indices correspond to the globally refined children, preserving their full intervals and the complete nested product for arbitrary coordinate values in any commutative monoid. Every marked physical subset corresponds to every interior index subset, with the correct relative complement, products and total sum. Independent kernel {session} passes 41 declarations and 14 substantive consumers with 55 standard-or-empty axiom traces. No domain is narrowed, no axiom is added, and no full inner-near/outer-far coefficient transport or factorization is inferred.',
 'mathematical_justification':[
 {'clause':'Consecutive positions mean actual cut membership','assessment':'BoundaryCutSet.Consecutive J requires both actual endpoints of J in the original cut set and excludes every cut strictly between them. It does not select an enumeration or assume a child is already known. part_consecutive follows because no natural index lies strictly between k and k+1; the converse finds the next original cut and uses the no-intervening-cut condition to force the right endpoint. part_injective follows from the strictly increasing original cut map. The independent actual_parts_are_exact_consecutive_pairs combines these into unique existence of the raw part index.'},
 {'clause':'Restriction and containment preserve all relevant positions','assessment':'consecutive_restrict_iff assumes only that J lies in the restricting interval whose two endpoints are retained. Every possible intervening cut is then in the restriction, proving equivalence of the actual predicate. A globally consecutive fine child starts in an existing half-open outer part; an outer right endpoint strictly inside it would be a retained fine cut, a contradiction. The fine child therefore lies wholly in that outer part. Its strictly positive length prevents containment in two ordered outer parts even when they share an endpoint. The independent unique-outer consumer verifies this exact existence/uniqueness statement.'},
 {'clause':'Actual near samples and their forced neighbors','assessment':'Consecutive intervals with a common left endpoint have the same right endpoint, since otherwise the smaller would intervene; the analogous right-endpoint statement fixes the previous cut. Thus a pair of consecutive intervals is uniquely determined by the middle position. IncreasingBoundaryTriple.leftInterval/rightInterval store the actual lower-middle and middle-upper entries. The nearTriple interval lemmas identify them with the two adjacent original composition parts, and its middle is the actual interiorPosition. Independent consumers prove unique existence of this triple at every interior index and equality of its sample under an arbitrary coefficient array. This fixes the actual neighboring positions, without assuming any geometric sign or scalar equality.'},
 {'clause':'Complete refined child-index bijection','assessment':'refinementInner is the exact raw composition reconstructed from the closed restriction of the refining cut set to an outer part. Each local child is globally consecutive by the restriction equivalence, and hence is one actual part of the globally sorted refinement. refinedChildIndex chooses that index and immediately proves equality of the complete child interval. Equality of two images forces equality of outer parts by positive-length containment uniqueness, then equality of their inner indices by raw part injectivity. Conversely every globally fine child belongs to an outer part and occurs among its recovered inner children. The resulting equivalence covers the entire dependent sigma of all inner child indices, with no excluded arity or boundary case.'},
 {'clause':'Actual nested coordinate product','assessment':'prod_refined_children rewrites the double product as a product over that full sigma domain and reindexes it by the proved interval-preserving bijection. For arbitrary X, equality of the child intervals gives equality of each actual factor, so no coordinate is replaced or omitted. The coefficient structure is only a CommMonoid, enough for this finite product reordering and weaker than the source CommRing. refinementInner_flatten recovers the original raw inner compositions exactly. Whole-family congruence then transfers the product to every original inner family, retaining dependent part counts and cut functions. The independent consumers check exact interval preservation, total child count, raw cut-map recovery, the product through the actual nestedMarkedCutEquiv output, and the all-inner-unary normalization.'},
 {'clause':'Every physical marking and exact relative complement','assessment':'indexMarks images any interior-index finset under the injective actual position map. markIndices filters the full interior-index universe by membership in the given physical marked set. Injectivity and previously proved physical-position coverage give both inverse laws. Complementary index subsets map to the refined interior cut set minus the selected marks, not to the complement in all Fin n boundary positions. Independent empty/full and relative-complement consumers verify that every marked and unmarked position stays strictly between the original endpoints and within the actual refinement.'},
 {'clause':'Selected products and all-marking sums','assessment':'prod_indexMarks uses injectivity to reindex the selected product with exactly the same physical argument. The inverse-law rewrite gives prod_markIndices; combining this with the relative complement theorem transports both marked and unmarked products. sum_all_indexMarks uses the full marked-subset equivalence for arbitrary AddCommMonoid-valued weights, so each possible marking appears once. Independent consumers prove there are exactly 2^(parts-1) physical markings and that the complete unary sum consists of the unique empty marking. The source arbitrary/empty/full subsets and unary cases are retained.'},
 {'clause':'Precise remaining factorization boundary','assessment':'These helpers supply the complete child-coordinate product identity and the induced arbitrary marked-index transport missing from the previous batch. ConsecutiveTriples supplies a criterion for matching near samples in a fixed cut set, but this batch does not yet carry each actual unmarked inner near triple into the global refinement and prove its coefficient equality there. It also does not transport the actual marked outer far triples or assemble those coefficient factors and child products through the weighted nested sum. Those remaining identifications are needed for Phi=F composed with G; no full factorization or farout consequence is certified here.'}],
 'independence':'The reviewer is distinct from the implementer and independently read the authoritative source and every frozen new definition/proof. The reviewer authored independent semantic consumers and checked exact input/output domains and actual factors, rather than inheriting root verdicts. Only new work/checks and work/reviews files were written; no implementation, source, map, root receipt or frozen prior review was changed.',
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_and_current_semantic_audit_pending':True,'full_farout_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Actual inner-near and outer-far coefficient transport through the full nested refinement map.','Complete weighted-sum factorization Phi(D,H)=F(H) composed with G(D).','All remaining far-only and restricted-subpolygon consequences of lem:farout.'],
 'not_certified':['No original acceptance for these four supporting helpers alone.','No full factorization, complete lem:farout, wall law, soft theorem, R theorem or stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/refinement-transport-prototype.json';write(out,d);print(out,sha(out));print('PASS:41 declarations+14 consumers,55 standard-or-empty traces; faithful explicit helper scope only.')
