from pathlib import Path
from hashlib import sha256
import json,re,datetime,sys
base=Path(__file__).resolve().parents[2]
def sha(p):return sha256((base/p).read_bytes()).hexdigest()
def load(p):return json.loads((base/p).read_text())
def write(p,d):(base/p).write_text(json.dumps(d,indent=2)+'\n')
session=int(sys.argv[1]);pfile='work/checks/critical-source-review-preparation.json';p=load(pfile)
assert sha(p['source'])==p['source_sha256'] and sha(p['trace'])==p['trace_sha256']
for key in ['SM_closure_files_sha256','root_files_sha256','root_receipts_sha256','inherited_review_binding','example_files_sha256']:
 for f,h in p[key].items():assert sha(f)==h,(key,f)
roots={f:load(f) for f in p['root_receipts_sha256']};assert all(r['exit_code']==0 for r in roots.values())
freshfile='work/reviews/critical-inverse-difference-independent.json';fresh=load(freshfile)
assert sha(freshfile)=='4293890be6f627208d9c2a68fe14d741629bb1923dafbd3069eaa69a46924fd0'
assert fresh['read_only'] and fresh['reviewer']=='/root/review_mark_transport'
for f,h in fresh['files_sha256'].items():assert sha(f)==h
for f,h in fresh['canonical_import_binding']['local_source_files_sha256'].items():assert sha(f)==h
for d in fresh['reviewed_declarations']:
 s=''.join((base/d['path']).read_text().splitlines(keepends=True)[d['first_line']-1:d['last_line']])
 assert s==d['text'] and sha256(s.encode()).hexdigest()==d['sha256']
domainfile='work/reviews/single-triple-n3-domain-note.json'
assert sha(domainfile)=='6c80aa7a8f9255bb5eff53aec13eefa32f59c830b564d997734ec36183b1d7ad'
logfile='work/checks/critical-source-review-types.log';s=(base/logfile).read_text();assert not re.search(r'error[:(]',s) and 'sorryAx' not in s
names=p['checked_declarations'];examples=p['additional_examples'];assert len(names)==53 and len(examples)==41
axioms={};types={}
for n in names+examples:
 m=re.search("'"+re.escape(n)+r"' depends on axioms:\s*\[([^]]*)\]",s)
 if m:axioms[n]=[x.strip() for x in m[1].split(',') if x.strip()]
 else:
  assert "'"+n+"' does not depend on any axioms" in s,n;axioms[n]=[]
 assert set(axioms[n])<={'propext','Classical.choice','Quot.sound'},n
for n in names:
 m=re.search(r'^'+re.escape(n)+r'(?:\.\{[^}]+\})?(?=\s)',s,re.M);assert m,n
 types[n]=s[m.start():s.index("'"+n+"'",m.start())].strip()
oldtypes={}
for f in ['far-only-locality-reviewed-types.json','critical-cut-reviewed-types.json','gap-split-products-reviewed-types.json']:
 for n,t in load('work/checks/'+f)['types'].items():
  if n in oldtypes:assert oldtypes[n]==t
  oldtypes[n]=t
assert len(oldtypes)==36 and all(types[n]==t for n,t in oldtypes.items())
typefile='work/checks/critical-source-reviewed-types.json'
write(typefile,{'types':types,'type_sha256':{n:sha256(t.encode()).hexdigest() for n,t in types.items()},'axioms':axioms,'checked_declarations':names,'additional_examples':examples,'consumer_count':41,'all_36_predecessor_types_unchanged':True,'trace_log':logfile,'trace_log_sha256':sha(logfile),'independent_kernel_session':session,'exit_code':0})
reviewed=dict(p['SM_closure_files_sha256'])
for n in p['body_order']:
 f='work/checks/'+n+'.body.lean';reviewed[f]=sha(f)
closurefile='work/checks/critical-source-review-closure.json'
write(closurefile,{'source':p['source'],'source_sha256':p['source_sha256'],'source_id':'thm:single-triple','SM_import_roots':['SM.Farout'],'SM_closure_files_sha256':p['SM_closure_files_sha256'],'SM_closure_count':32,'reviewed_files_sha256':reviewed,'root_receipts_sha256':p['root_receipts_sha256'],'root_files_sha256':p['root_files_sha256'],'inherited_review_binding':p['inherited_review_binding'],'preparation':pfile,'preparation_sha256':sha(pfile),'trace':p['trace'],'trace_sha256':sha(p['trace']),'fresh_inverse_difference_review':freshfile,'fresh_inverse_difference_review_sha256':sha(freshfile),'separate_source_domain_note':domainfile,'separate_source_domain_note_sha256':sha(domainfile),'scope':p['scope']})
prior=load('work/reviews/lem-farout.json');failed=dict(p['prior_failed_independent_run'])
failed['source_sha256']=sha(failed['source']);failed['log_sha256']=sha(failed['log'])
provenance={'method_overlap_declaration':'SM.critical_proper_child_coordinates','matching_prior_consumer':'FarOnlyLocalityIndependentReview.every_proper_critical_child','prior_consumer_file':'work/checks/far-only-locality-review-examples.lean','prior_consumer_file_sha256':sha('work/checks/far-only-locality-review-examples.lean'),'implementer_disclosure':'Implementer stated that the lemma was authored directly from canonical locality and strict child-leaf APIs, without reading or copying the earlier consumer source; implementer had read the reviewer report describing that same leaf-bound argument.','treatment':'The conceptual overlap is disclosed and the entire four-declaration CriticalInverseDifference body receives a fresh noncontributing source/proof review rather than relying on this reviewer alone.','fresh_noncontributing_reviewer':fresh['reviewer'],'fresh_review':freshfile,'fresh_review_sha256':sha(freshfile),'fresh_review_is_read_only_without_new_kernel':True,'current_independent_kernel_checks_all_four':True,'scope_resolved_by_combined_reviews':True}
evidence={'independent_trace_source':p['trace'],'independent_trace_source_sha256':sha(p['trace']),'independent_trace_log':logfile,'independent_trace_log_sha256':sha(logfile),'independent_kernel_command':'lake env lean ../checks/critical-source-review-types.lean','independent_kernel_session':session,'independent_kernel_exit_code':0,'first_independent_run_passed':False,'prior_failed_independent_run':failed,'checked_declarations':names,'declaration_count':53,'new_declaration_count':17,'all_36_predecessor_types_unchanged':True,'declaration_axioms':{n:axioms[n] for n in names},'additional_examples':examples,'additional_example_count':41,'new_consumer_count':10,'additional_examples_passed':True,'additional_example_axioms':{n:axioms[n] for n in examples},'transparent_predicates_printed':p['transparent_definitions_printed'],'reviewed_types':typefile,'reviewed_types_sha256':sha(typefile),'independent_closure_evidence':closurefile,'independent_closure_evidence_sha256':sha(closurefile),'root_successful_results':roots,'root_receipts_sha256':p['root_receipts_sha256'],'fresh_inverse_difference_review':freshfile,'fresh_inverse_difference_review_sha256':sha(freshfile),'scope_note':'Eight exact frozen external bodies over the actual32-module canonical Farout closure. All36 predecessor types match prior independent traces. All31 prior consumers and10 new actual response consumers pass. Fresh noncontributing review covers all four inverse-difference declarations with conceptual prior-consumer overlap explicitly disclosed.'}
d={'review_schema':'independent-partial-source-prototype-review-v1','id':'critical-source-response-prototype','source_id':'thm:single-triple','source_line':229,'source':p['source'],'source_sha256':p['source_sha256'],'source_lines':p['source_lines'],'additional_source_sha256':prior['additional_source_sha256'],'reviewer':'review_relgp_full-independent-20260911','implementer':'root-implementation-20260910','verdict':'faithful','implemented_scope_verdict':'faithful','parameters_reviewed':True,'definition_equivalence_reviewed':True,'source_claim_accepted':False,'statement_sha256':None,'in_theorem_library':False,'utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'main_declarations':[n for b in p['new_body_names'] for n in p['checked_declarations_by_body'][b]],'main_declarations_by_body':{b:p['checked_declarations_by_body'][b] for b in p['new_body_names']},'prototype_files_sha256':{n:sha('work/checks/'+n+'.prototype.lean') for n in p['body_order']},'reviewed_files_sha256':reviewed,'import_closure_roots':['SM.Farout'],'import_closure_file_count':32,'embedded_body_count':8,'inherited_review_binding':p['inherited_review_binding'],'evidence':evidence,'pins':prior['pins'],'provenance_disclosure':provenance,
 'reason':f'Faithful actual critical inverse/output response in algebraic fixed-endpoint gap form. The full transform subtraction retains the unary coordinate difference; equality of every proper child c is derived from locality and strict leaf bounds. The two actual inverse equations then give the negative ordinary coefficient sum, while the actual reversed output adds its separate coefficient sum. Exact fixed-endpoint gates, one-gate physical erasure, the complete middle-cut partition and full gap product bijection factor both coefficient responses. Substitution yields positive delta times both ordinary gap sums for the actual c jump and positive delta times the sum of ordinary and reversed gap products for the actual B jump. Independent second kernel {session} passes53 declarations and41 consumers with94 standard-or-empty traces; all36 previous types match. Fresh noncontributing review resolves disclosed method overlap for the proper-child lemma. Geometric epsilon/E/B identification and propagation remain pending, so the original wall theorem is not accepted.',
 'mathematical_justification':[
 {'clause':'Subtraction of the actual complete transforms','assessment':'farTransform_difference_of_proper_children rewrites both actual Phi(0,H) coordinate equations into the exact triangular form: one unary coordinate plus every raw nonunary composition. Its explicit generic hypothesis equates both child arrays on every actual child of each nonunary composition. Product congruence therefore replaces all child factors of the second sum by the first array factors. Finite sum subtraction and distributivity isolate the coefficient difference for each unchanged child product. The unary coordinate difference remains once with coefficient one. An independent consumer specializes equal H arrays and verifies that only the actual unary change remains.'},
 {'clause':'Proper child equality is derived for the actual c arrays','assessment':'critical_proper_child_coordinates applies established off-critical-span locality to every child of a raw nonunary composition of the exact critical span. The strict child-leaf bound proves its leaf count is smaller than the span. If that child contained both critical endpoints, its endpoint inequalities would force its leaf count to be at least the span length, contradicting the bound. Thus the local theorem applies with no assumed response or additional child condition. This is the same elementary method as an earlier reviewer consumer; the implementer disclosed independent authorship from canonical APIs after reading the reviewer report. To remove any independence ambiguity, a fresh noncontributing reviewer independently checked all four CriticalInverseDifference source statements and proofs; its report and exact fragments are hash-bound here.'},
 {'clause':'Actual inverse equations give the negative coefficient sum','assessment':'The generic transform-difference identity is instantiated with farOnlyCoordinates(H1) and farOnlyCoordinates(H2), using the derived proper-child equality. Their defining proved equations are F_H(c)=E, so subtracting them gives zero on the left because the target is the identical actual E array. The resulting equality is zero equals the unary c difference plus the nonunary ordinary coefficient response. Moving the latter to the other side gives exactly critical_inverse_difference with the negative sign. Neither existence of a solution nor the jump formula is a premise; c is the actual constructed triangular inverse.'},
 {'clause':'Reversed output retains both distinct sources of change','assessment':'farOnlyOutput(H) is F_(-H) applied to the same c(H). Applying the generic transform identity to -H1,-H2 and those actual c arrays yields the same unary c difference plus a separately evaluated reversed-far coefficient difference. This is critical_output_difference. The independent response consumer rewrites the actual B change as the reversed coefficientDifferenceSum minus the ordinary coefficientDifferenceSum, checking both contribution signs before any factorization.'},
 {'clause':'Actual fixed-endpoint scalar gates','assessment':'cutWeightedSum is the complete sum over all raw interval compositions of physical interior-position factors and actual child-coordinate factors, including the unary composition. Its bridge to farTransform requires equality of each sampled scalar with the actual far gate and proves the full identity by finite product/sum congruence. fixedFarGate(t,H,x) uses precisely the fixed critical lower/upper endpoints and physical x when x lies strictly inside that span; outside it is zero. Every sampled whole-span interior position is proved strict before the formula is used. Structure equality then identifies this actual triple with the original farTriple. An independent consumer checks the middle gate is -H(t)/2 and another verifies the unused outside values, so no unrelated array or zero determinant is substituted.'},
 {'clause':'Gate reversal and exact physical erasure','assessment':'fixedFarGate_neg proves pointwise reversal at every physical position, including the outside zero branch. fixedFarGate_weight rewrites the complete whole-span far coefficient using the exact fixed-endpoint scalar samples. For a MiddleComposition, the already proved unique critical far index is selected, its actual interiorPosition is identified with t.middle, and the one-gate difference formula is applied. Every retained far factor is rewritten as fixedFarGate(H1) at the same actual physical position. The proved index-to-position erasure then replaces univ.erase k by the true interior set with t.middle erased. This proves the physical coefficient response without division or cancellation, preserving zero-factor cases already checked in the prior gap-product consumers.'},
 {'clause':'Complete coefficient sums and exact removal of the unary term','assessment':'coefficientDifferenceSum is defined on every original raw composition, with the child array held fixed. For the unary composition both far weights equal one, so its difference is exactly zero. Splitting out that one composition and applying the proved nonSingleEquiv gives equality with precisely all compositions of parts>=2. No other term is removed. An independent consumer unfolds the definitions and identifies this sum with the actual difference F_H2(X)-F_H1(X) at fixed X, confirming its complete raw domain and orientation.'},
 {'clause':'Full ordinary and reversed coefficient responses','assessment':'The complete coefficient sum is partitioned by actual membership of the critical middle cut. Every no-middle term vanishes because its far coefficient is unchanged. On the remaining full MiddleComposition domain, the physical one-gate difference formula supplies negative delta times the erased interior product and every child factor. Finite distributivity extracts the common scalar and the already proved entire erased-gap weighted sum factors the rest into both full gap sums. The reversed response repeats this argument on -H1,-H2 and simplifies to positive delta with reversed fixed gates. No weighted response formula or product equivalence is assumed as a premise; the exact prior splitting/child/erased-product proofs supply them.'},
 {'clause':'Actual critical c and B source jumps','assessment':'critical_inverse_source_jump first replaces the nonunary coefficient sum in the actual inverse-difference theorem by its equal complete sum, substitutes its ordinary negative-delta factorization, and negates it. The result is positive delta times the product of both ordinary fixed-endpoint gap sums evaluated on c(H1). critical_output_source_jump substitutes the independent reversed positive-delta coefficient response into the actual output-difference theorem and adds that derived unary jump. Factoring delta gives the sum of ordinary and reversed gap products with both plus signs. Both conclusions concern the actual inverse/output arrays, not a hypothetical response object.'},
 {'clause':'Independent actual-response consumers and scalar generality','assessment':'The new consumers verify the full-span weighted sum against the actual far transform, both response formulas at an arbitrary scalar delta, vanishing when the critical entry agrees, reversal of side orientation using the opposite baseline, and an arbitrary single-entry Function.update with the actual constructed inverse. They also check the decomposition into reversed minus ordinary complete coefficient responses. All previous unary-gap, empty-product, zero-factor, full child and erased-sum consumers rerun unchanged. The ring is arbitrary commutative with invertible two; delta is not assumed to be +/-1, no field or nontriviality premise is introduced, and no geometric G1/G2 hypothesis appears in these algebraic results.'},
 {'clause':'Geometric identification and n=3 source interpretation remain separate','assessment':'The gap sums here use the original critical endpoints in their scalar function. Identifying them with the natural gap E/B values requires the source wall epsilon identities and actual nondegenerate wall data; those geometric steps are not proved in this batch. A separately bound source note records that singleton Zpt alone only concerns distinct labels and does not force geometrically distinct center points at n=3. The printed theorem also explicitly uses pairwise distinct vertices and distinct xi on its line representation. That geometric reading must be made explicit rather than silently inferred or replaced by n>=4. The note gives an elementary collapsing-triangle example refuting only the inference from singleton Zpt, not the theorem with its printed geometric data. This issue does not change or invalidate the present arbitrary-array algebra.'},
 {'clause':'Remaining original theorem scope','assessment':'The reviewed four new bodies now establish actual algebraic critical-span inverse/output jumps with explicit fixed-endpoint gap products. They do not establish wall-germ common sign stabilization, geometric epsilon signs and E/B gap identification, the contracted polygon with its physical root, larger-interval propagation, or the final proper-span wall-response formula. Even the full-span geometric formula needs the geometric identification step. The whole thm:single-triple is therefore not accepted by this partial review, and all source/map/canonical changes remain outside reviewer authority.'}],
 'independence':'This reviewer independently read the full relevant source, all four new frozen bodies and their transparent actual definitions, and wrote only review consumers/evidence. No implementation, source, map, root receipt or frozen report was edited. The conceptual overlap between the proper-child proof and an earlier consumer is disclosed, with implementer authorship explanation and the fresh noncontributing all-four-declaration review bound explicitly. That fresh review did not run a kernel; the current independent run supplies full actual types and standard axiom evidence. Earlier Farout marking-fragment provenance remains bound through its existing separate reviews. First-run reviewer-only proof errors were preserved and corrected without changing any statement.',
 'separate_source_domain_note':domainfile,'separate_source_domain_note_sha256':sha(domainfile),
 'accounting':{'original_claims_accepted':0,'proof_increment':0,'definition_increment':0,'canonical_port_pending':True,'full_single_triple_accepted':False,'stage_complete':False},
 'unproved_original_clauses_in_this_reviewed_batch':['Wall geometric sign stability and epsilon/E/B identification on both gap sums.','Explicit resolution of geometric-distinctness interpretation for the n>=3 source domain.','Contracted polygon, G1 and physical root identification.','Larger-interval propagation and both final geometric wall formulas.'],
 'not_certified':['No original thm:single-triple acceptance or canonical semantic hash.','The n=3 note is not a Lean-verified counterexample to the full printed theorem.','No complete corner wall law, soft theorem, R theorem or overall stage completion.']}
for f,h in d['additional_source_sha256'].items():assert sha(f)==h
out='work/reviews/critical-source-response-prototype.json';write(out,d);print(out,sha(out));print('PASS:53 declarations+41 consumers;94 standard-or-empty traces;36 predecessor types unchanged; actual algebraic critical source response only; no original acceptance.')
