#!/usr/bin/env python3
"""Generate docs/statement_closure.md: every declaration the type of SM.corner_laws_and_soft unfolds to,
as recorded by the checker's audit (semantic_dependencies of the final declaration), located in work/lean by a
namespace-aware scan. Usage: python3 statement_closure.py [PACKAGE_ROOT]  (default: ../../CORNER_LAWS_FOCUSED_20260912)."""
import json, gzip, re, os, sys, collections, pathlib
ROOT = pathlib.Path(sys.argv[1] if len(sys.argv) > 1 else pathlib.Path(__file__).resolve().parents[2] / "CORNER_LAWS_FOCUSED_20260912").resolve()
OUT = pathlib.Path(__file__).resolve().parents[1] / "statement_closure.md"
d = json.load(gzip.open(ROOT / "work/delivery/receipts/declaration-audit.json.gz", "rt"))
decls = d["audit"]["declarations"]
final = next(x for x in decls if x["declaration"] == "SM.corner_laws_and_soft")
deps = final["semantic_dependencies"]
DECL = re.compile(r"^\s*(?:@\[[^\]]*\]\s*)*(?:(?:private|protected|noncomputable|partial|unsafe|nonrec|scoped|local)\s+)*"
                  r"(def|theorem|lemma|structure|inductive|class|instance|abbrev|opaque|axiom)\s+([A-Za-z_][\w.!?']*)")
index = collections.defaultdict(list)
lean = ROOT / "work/lean"
for p in sorted(lean.rglob("*.lean")):
    if ".lake" in p.parts: continue
    ns = []
    for ln, line in enumerate(open(p, encoding="utf-8", errors="replace"), 1):
        m = re.match(r"^\s*namespace\s+([\w.]+)", line)
        if m: ns.append(m.group(1)); continue
        m = re.match(r"^\s*end\s+([\w.]+)\s*$", line)
        if m and ns and ns[-1] == m.group(1): ns.pop(); continue
        m = DECL.match(line)
        if m:
            full = (".".join(ns) + "." if ns else "") + m.group(2)
            index[full].append((str(p.relative_to(lean)), ln, m.group(1)))
def locate(n):
    if n in index: return index[n][0]
    parts = n.split(".")
    for k in range(len(parts) - 1, 0, -1):          # projections / constructors: the parent declaration
        parent = ".".join(parts[:k])
        if parent in index: return index[parent][0]
    return None
rows = sorted(((x["declaration"], x["kind"], locate(x["declaration"])) for x in deps),
              key=lambda r: (r[2][0] if r[2] else "~", r[2][1] if r[2] else 0))
unresolved = [n for n, _, loc in rows if loc is None]
kinds = collections.Counter(k for _, k, _ in rows)
byfile = collections.Counter(loc[0] for _, _, loc in rows if loc)
out = ["# What the final statement unfolds to", "",
       "The type of `SM.corner_laws_and_soft` is the `Prop` structure `SM.CornerLawsAndSoftData`. Reading that statement means reading the",
       "definitions it is built from. The checker's audit (`work/delivery/receipts/declaration-audit.json.gz`, `semantic_dependencies` of the",
       "final declaration) lists them: **%d declarations**, all in the `SM` namespace, on top of Mathlib. Proofs are not part of this list:" % len(rows),
       "the lemmas below appear only because a definition uses them (well-definedness, decidability, a chosen witness).", "",
       "| Kind | Count |", "|---|---|"] + [f"| {k} | {v} |" for k, v in sorted(kinds.items(), key=lambda kv: -kv[1])] + ["",
       "The one axiom in the list is `SM.lit_homfly`: the HOMFLY map `SM.homfly` is defined as its chosen witness, so the *definition* of the state",
       "sum already refers to the admitted HOMFLY-PT interface. The other five literature constants enter through proofs only.", "",
       f"Grouped by file ({len(byfile)} files under `work/lean/`), in file order. Generated by `docs/graph/statement_closure.py`.", ""]
cur = None
for n, k, loc in rows:
    f = loc[0] if loc else "(not located)"
    if f != cur:
        out += ["", f"### `{f}`", "", "| Declaration | Kind | Line |", "|---|---|---|"]; cur = f
    out.append(f"| `{n}` | {k} | {loc[1] if loc else ''} |")
OUT.write_text("\n".join(out) + "\n")
print(f"wrote {OUT}: {len(rows)} declarations, {len(byfile)} files, unresolved {len(unresolved)} {unresolved[:5]}")
